kona-crypto/src/main/java/com/tencent/kona/sun/security/util/ECParameters.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/AlgorithmId.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/DNSName.java
This is a backport of [JDK-8283800]: Simplify String.indexOf/lastIndexOf calls.
This PR will resolve #11.
[JDK-8283800]:
<https://bugs.openjdk.org/browse/JDK-8283800>
=> TKSS-11: Backport JDK-8283800: Simplify String.indexOf/lastIndexOf calls

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS7.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/AuthorityInfoAccessExtension.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/DeltaCRLIndicatorExtension.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/FreshestCRLExtension.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/IssuingDistributionPointExtension.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/SubjectInfoAccessExtension.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CRLImpl.java
This is a backport of [JDK-8283525]: http://tools.ietf.org/html/* URLs return 404
This PR will resolve #13.
[JDK-8283525]:
<https://bugs.openjdk.org/browse/JDK-8283525>
=> TKSS-13: Backport JDK-8283525: http://tools.ietf.org/html/* URLs return 404

kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/X509Key.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/CRLExtensions.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CertImpl.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CertInfo.java
This is a backport of [JDK-8284415]: Collapse identical catch branches in security libs.
This PR will resolve #15.
[JDK-8284415]:
<https://bugs.openjdk.org/browse/JDK-8284415>
=> TKSS-15: Backport JDK-8284415: Collapse identical catch branches in security libs

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/BitArray.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/JavaKeyStore.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/CertId.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/RevocationChecker.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/AccessDescription.java
This is a backport of [JDK-8289274]: Cleanup unnecessary null comparison before instanceof check in security modules.
This PR will resolve #17.
[JDK-8289274]:
<https://bugs.openjdk.org/browse/JDK-8289274>
=> TKSS-17: Backport JDK-8289274: Cleanup unnecessary null comparison before instanceof check in security modules

kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/AlgorithmId.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/util/SignatureUtil.java
This a backport of [JDK-8286908]: ECDSA signature should not return parameters.
This PR will resolve #19.
[JDK-8286908]:
<https://bugs.openjdk.org/browse/JDK-8286908>
=> TKSS-19: Backport JDK-8286908: ECDSA signature should not return parameters

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SessionTicketExtension.java
This is backport of [JDK-8277307]: Pre shared key sent under both session_ticket and pre_shared_key extensions.
This PR will resolve #21.
[JDK-8277307]:
<https://bugs.openjdk.org/browse/JDK-8277307>
=> TKSS-21: Backport JDK-8277307: Pre shared key sent under both session_ticket and pre_shared_key extensions

kona-pkix/src/main/java/com/tencent/kona/sun/security/timestamp/HttpTimestamper.java
This is backport of [JDK-8289572]: InputStream wrapping with BufferedInputStream is redundant in HttpTimestamper.
This PR will resolve #23.
[JDK-8289572]:
<https://bugs.openjdk.org/browse/JDK-8289572>
=> TKSS-23: Backport JDK-8289572: InputStream wrapping with BufferedInputStream is redundant in HttpTimestamper

kona-crypto/build.gradle.kts, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Cipher.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2Test.java, kona-pkix/build.gradle.kts
BouncyCastle just released 1.72.
This version resolves a SM2 encryption issue, which may lead to infinite loop.
The fix is https://github.com/bcgit/bc-java/commit/58940b9c3e99b70f3cc43c00b9f1f6f1e87f1cc6
This PR will resolve #27.
=> TKSS-27: Upgrade BC to 1.72

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECKeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/ObjectIdentifier.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Oid.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificateRequest.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCipher.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPServerHello.java
Although https://github.com/Tencent/TencentKonaSMSuite/issues/25 cleaned up the classes from OpenJDK, the classes for TLCP only should also be cleaned up.
This PR will resolve #31.
=> TKSS-31: Cleanup on TLCP classes

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerOutputStream.java
This is a backport of [JDK-8294987]: Streamline DerOutputStream write.
This PR will resolve #35.
[JDK-8294987]:
<https://bugs.openjdk.org/browse/JDK-8294987>
=> TKSS-35: Backport JDK-8294987: Streamline DerOutputStream write

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/Curve25519OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/Curve448OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial448.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP256.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP384.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialSM2.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P256OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P384OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P521OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/SM2OrderField.java, kona-crypto/src/test/java/com/tencent/kona/sun/security/util/math/intpoly/FieldGen.java
This is a backport of [JDK-8294997]: Improve ECC math operations.
This PR will resolve #39.
[JDK-8294997]:
<https://bugs.openjdk.org/browse/JDK-8294997>
=> TKSS-39: Backport JDK-8294997: Improve ECC math operations

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECDSASignature.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/ECUtil.java
This is a backport of [JDK-8288508]: Enhance ECDSA usage.
This JBS is a security issue, though it has no CVE.
This PR resolves #45.
[JDK-8288508]:
<https://bugs.openjdk.org/browse/JDK-8288508>
=> TKSS-45: Backport JDK-8288508: Enhance ECDSA usage

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLContextImpl.java
This is a backport of [JDK-8256660]: Disable DTLS 1.0.
Although DTLS has nothing to do with TLCP, it would be better to align the codes with the OpenJDK's.
This PR will resolve #61.
[JDK-8256660]:
<https://bugs.openjdk.org/browse/JDK-8256660>
=> TKSS-61: Backport of JDK-8256660: Disable DTLS 1.0

kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/JavaKeyStore.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CRLEntryImpl.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CRLImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSessionImpl.java
This is a backport of [JDK-8295953]: Use enhanced-for cycle instead of Enumeration in sun.security.
This PR will resolve #68.
[JDK-8295953]:
<https://bugs.openjdk.org/browse/JDK-8295953>
=> TKSS-68: Backport JDK-8295953: Use enhanced-for cycle instead of Enumeration in sun.security

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Cipher.java
This is a backport [JDK-8293886]: The abstract keyword can be removed in AESCipher.
This PR will resolve #71.
[JDK-8293886]:
<https://bugs.openjdk.org/browse/JDK-8293886>
=> TKSS-71: Backport JDK-8293886: The abstract keyword can be removed in AESCipher

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/EDIPartyName.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/GeneralSubtrees.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X400Address.java
This is a backport of [JDK-8296741]: Illegal X400Address and EDIPartyName should not be created.
This PR will resolve #77.
[JDK-8296741]:
<https://bugs.openjdk.org/browse/JDK-8296741>
=> TKSS-77: Backport JDK-8296741: Illegal X400Address and EDIPartyName should not be created

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/CertificateValidity.java
This is a backport of [JDK-8296900]: CertificateValidity fields are not optional.
This PR will resolve #78.
[JDK-8296900]: 
<https://bugs.openjdk.org/browse/JDK-8296900>
=> TKSS-78: Backport JDK-8296900: CertificateValidity fields are not optional

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java, kona-crypto/src/main/java/com/tencent/kona/java/nio/DirectBufferUtil.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
```
java.lang.IllegalAccessError:
class com.tencent.kona.crypto.provider.GaloisCounterMode$GCMEngine (in unnamed module @0x2d58d9ed) 
cannot access class sun.nio.ch.DirectBuffer (in module java.base)
because module java.base does not export sun.nio.ch to unnamed module @0x2d58d9ed
at com.tencent.kona.crypto.provider.GaloisCounterMode$GCMEngine.overlapDetection(GaloisCounterMode.java:929)
at com.tencent.kona.crypto.provider.GaloisCounterMode$GCMEncrypt.doFinal(GaloisCounterMode.java:1318)
at com.tencent.kona.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:452)
at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
at com.tencent.kona.sun.security.ssl.TLCPCipher$TLCPGcmWriteCipherGenerator$GcmWriteCipher.encrypt(TLCPCipher.java:522)
at …
```
=> TKSS-76: Cannot access sun.nio.ch.DirectBuffer on JDK 17

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS9Attribute.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/SigningCertificateInfo.java
This is a backport of [JDK-8296736]: Some PKCS9Attribute can be created but cannot be encoded.
This PR will resolve #81.
[JDK-8296736]:
<https://bugs.openjdk.org/browse/JDK-8296736>
=> TKSS-81: Backport JDK-8296736: Some PKCS9Attribute can be created but cannot be encoded

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/IntegerModuloP.java
This is a backport of [JDK-8294731]: Improve multiplicative inverse for secp256r1 implementation.
This PR will resolve #82.
[JDK-8294731]:
<https://bugs.openjdk.org/browse/JDK-8294731>
=> TKSS-82: Backport of JDK-8294731: Improve multiplicative inverse for secp256r1 implementation

kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/AlgorithmId.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/MacData.java
This is a backport of [JDK-8296442]: EncryptedPrivateKeyInfo can be created with an uninitialized AlgorithmParameters.
This PR will resolve #83.
[JDK-8296442]:
<https://bugs.openjdk.org/browse/JDK-8296442>
=> TKSS-83: Backport JDK-8296442: EncryptedPrivateKeyInfo can be created with an uninitialized AlgorithmParameters

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CRLImpl.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CertImpl.java
This is a backport of [JDK-8296901]: Do not create unsigned certificate and CRL.
This is PR will resolve #85.
[JDK-8296901]:
<https://bugs.openjdk.org/browse/JDK-8296901>
=> TKSS-85: Backport JDK-8296901: Do not create unsigned certificate and CRL

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/IPAddressName.java
This is a backport of [JDK-8267617]: Certificate's IP x509 NameConstraints raises ArrayIndexOutOfBoundsException.
This PR will resolve #102.
[JDK-8267617]:
https://bugs.openjdk.org/browse/JDK-8267617
=> TKSS-102: Backport JDK-8267617: Certificate's IP x509 NameConstraints raises ArrayIndexOutOfBoundsException

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java
This is a backport of [JDK-8296507]: GCM using more memory than necessary with in-place operations.
This PR will resolve #101.
[JDK-8296507]:
<https://bugs.openjdk.org/browse/JDK-8296507>
=> TKSS-101: Backport JDK-8296507: GCM using more memory than necessary with in-place operations

kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM2SignaturePerfTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2Test.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java, kona-provider/src/test/java/com/tencent/kona/crypto/SM2Test.java
It should call setParameter before init.
For example,
```
--- a/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2Test.java
+++ b/kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2Test.java
@@ -418,8 +418,8 @@ public class SM2Test {
= new SM2SignatureParameterSpec(ID, (ECPublicKey) pubKey);
Signature signer = Signature.getInstance("SM2", PROVIDER);
-        signer.initSign(priKey);
signer.setParameter(paramSpec);
+        signer.initSign(priKey);
signer.update(MESSAGE, 0, MESSAGE.length / 2);
signer.update(MESSAGE, MESSAGE.length / 2,
```
This PR will resolve #107.
=> TKSS-107: Call setParameter before init

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateVerify.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/DHKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/DHServerKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ECDHKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ECDHServerKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/HandshakeContext.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/KeyShareExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/NamedGroup.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EServerKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLConfiguration.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SupportedGroupsExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/X509Authentication.java
This is a backport of [JDK-8281236]: (D)TLS key exchange named groups.
Although it should not use the new JDK public APIs on named groups in class javax.net.ssl.SSLParameters, it would be better to sync the code changes in package sun.security.ssl as much as possible.
This PR will resolve #110.
[JDK-8281236]:
<https://bugs.openjdk.org/browse/JDK-8281236>
=> TKSS-110: Backport JDK-8281236: (D)TLS key exchange named groups

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3Engine.java
It would be better to use lower SM3Engine instead of higher SM3MessageDigest.
And it should use a local digest buffer on deriving key.
This PR will resolve #114.
=> TKSS-114: SM2KeyAgreement would use SM3Engine instead of SM3MessageDigest

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/SignerInfo.java
This is a backport of [JDK-8299746]: Accept unknown signatureAlgorithm in PKCS7 SignerInfo.
This PR will resolve #118.
[JDK-8299746]:
<https://bugs.openjdk.org/browse/JDK-8299746>
=> TKSS-118: Backport JDK-8299746: Accept unknown signatureAlgorithm in PKCS7 SignerInfo

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLContextImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSessionContextImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SessionTicketExtension.java
This is a backport of [JDK-8298381]: Improve handling of session tickets for multiple SSLContexts.
This PR will resolve #119.
[JDK-8298381]:
<https://bugs.openjdk.org/browse/JDK-8298381>
=> TKSS-119: Backport JDK-8298381: Improve handling of session tickets for multiple SSLContexts

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/SecurityProviderConstants.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/PredefinedDHParameterSpecs.java
This is a backport of JDK-8293554: Enhanced DH Key Exchanges.
Commit: https://github.com/openjdk/jdk17u/commit/88b952a035f5fe8a337bb66ef13da607112948a2
This PR will resolve #122.
=> TKSS-122: Backport JDK-8293554: Enhanced DH Key Exchanges

kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/OCSP.java
This is a backport of [JDK-8296343]: CPVE thrown on missing content-length in OCSP response.
This PR will resolve #137.
[JDK-8296343]:
<https://bugs.openjdk.org/browse/JDK-8296343>
=> TKSS-137: Backport [JDK-8296343]: CPVE thrown on missing content-length in OCSP response

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Debug.java
This is a backport of [JDK-8294527]: Some java.security.debug options missing from security docs.
This PR will resolve #138.
[JDK-8294527]:
<https://bugs.openjdk.org/browse/JDK-8294527>
=> TKSS-138: Backport JDK-8294527: Some java.security.debug options missing from security docs

kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/AlgorithmId.java
This is a backport [JDK-8301788]: AlgorithmId should keep lowercase characters from 3rd party providers.
This PR will resolve #139.
[JDK-8301788]:
<https://bugs.openjdk.org/browse/JDK-8301788>
=> TKSS-139: Backport JDK-8301788: AlgorithmId should keep lowercase characters from 3rd party providers

kona-pkix/src/main/java/com/tencent/kona/pkix/PKIXUtils.java, kona-pkix/src/test/java/com/tencent/kona/pkix/util/PKIXUtilsTest.java
Provides a utility for generating a PublicKey instance from a X.509-encoded public key.
This PR will resolves #145.
=> TKSS-145: Parse X.509-encoded public key

kona-crypto/src/main/java/com/tencent/kona/crypto/spec/RFC5915EncodedKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECKeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/RFC5915Key.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParametersTest.java, kona-pkix/src/main/java/com/tencent/kona/pkix/PKIXUtils.java, kona-pkix/src/test/java/com/tencent/kona/pkix/util/PKIXUtilsTest.java
RFC 5915
```
ECPrivateKey ::= SEQUENCE {
version        INTEGER { ecPrivkeyVer1(1) } (ecPrivkeyVer1),
privateKey     OCTET STRING,
parameters [0] ECParameters {{ NamedCurve }} OPTIONAL,
publicKey  [1] BIT STRING OPTIONAL
}
```
This PR will resolve #146.
=> TKSS-146: Support RFC 5915-compliant encoded private key

.github/workflows/gradle-build.yaml, buildSrc/src/main/kotlin/kona-common.gradle.kts
It would be better to run the tests on macOS and Windows while submitting the PRs.
This PR will resolve #156.
=> TKSS-156: GitHub actions support macOS and Windows

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/DHKeyExchange.java
This is a Backport of [JDK-830170]: Increase the default TLS Diffie-Hellman group size from 1024-bit to 2048-bit.
This PR will resolve #163.
[JDK-830170]:
<https://bugs.openjdk.org/browse/JDK-8301700>
=> Backport JDK-830170: Increase the default TLS Diffie-Hellman group size from 1024-bit to 2048-bit

kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAKeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAKeyPairGenerator.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPrivateCrtKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPrivateKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPublicKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSASignature.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAUtil.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLConfiguration.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLEngineImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Utilities.java
In order to support older JDK 8 releases, say 8u242, it should allow the codes not to depend on [RSASSA-PSS signature] and [ALPN] implementations on runtime.
Both of these features were introduced by JDK 8u242.
This PR will resolve #168.
[RSASSA-PSS signature]:
<https://bugs.openjdk.org/browse/JDK-8230978>
[ALPN]:
<https://bugs.openjdk.org/browse/JDK-8230977>
=> TKSS-168: May not depend on RSASSA-PSS signature and ALPN on runtime

kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/AlgorithmId.java, kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java
This is a backport of [JDK-8301793]: AlgorithmId should not encode a missing parameters field as NULL unless hardcoded.
This PR will resolve #170.
[JDK-8301793]:
<https://bugs.openjdk.org/browse/JDK-8301793>
=> TKSS-170: Backport JDK-8301793: AlgorithmId should not encode a missing parameters field as NULL unless hardcoded

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Engine.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2Test.java
If the public key is invalid, SM2Engine::decrypt would raise BadPaddingException rather than a runtime exception like IllegalArgumentException.
This PR will resolve #175.
=> TKSS-175: SM2 decryption would raise BadPaddingException on invalid public key

README.md, README_cn.md
The READMEs just use some version placeholders instead of the exact latest versions.
This PR will resolves #179.
=> TKSS-179: READMEs just use version placeholders

kona-pkix/src/test/java/com/tencent/kona/pkix/SimpleOCSPServer.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/CertPathValidatorTest.java
This is a backport of [JDK-8300939]: sun/security/provider/certpath/OCSP/OCSPNoContentLength.java fails due to network errors.
This PR will resolve #181.
[JDK-8300939]:
<https://bugs.openjdk.org/browse/JDK-8300939>
=> TKSS-181: Backport of JDK-8300939: sun/security/provider/certpath/OCSP/OCSPNoContentLength.java fails due to network errors

build.gradle.kts, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/DistributionPointFetcher.java
This is a backport of [JDK-8296400]: pointCrlIssuers might be null in DistributionPointFetcher::verifyURL.
This PR will resolve #191.
[JDK-8296400]:
<https://bugs.openjdk.org/browse/JDK-8296400>
=> TKSS-191: Backport of JDK-8296400: pointCrlIssuers might be null in DistributionPointFetcher::verifyURL

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLEngineInputRecord.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSocketInputRecord.java
This is a backport of [JDK-8182621]: JSSE should reject empty TLS plaintexts.
This PR will resolve #194.
[JDK-8182621]:
<https://bugs.openjdk.org/browse/JDK-8182621>
=> TKSS-194: Backport of JDK-8182621: JSSE should reject empty TLS plaintexts

.github/workflows/gradle-build.yaml
It would upgrade gradle-build-action to version 2.4.2 due to [a security issue].
This PR will resolve #208.
[a security issue]:
<https://github.com/Tencent/TencentKonaSMSuite/security/dependabot/1>
=> TKSS-208: Upgrade gradle-build-action to version 2.4.2

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/HandshakeContext.java
This is a backport of [JDK-8294983]: SSLEngine throws ClassCastException during handshake.
This PR will resolve #210.
[JDK-8294983]:
<https://bugs.openjdk.org/browse/JDK-8294983>
=> TKSS-210: Backport of JDK-8294983: SSLEngine throws ClassCastException during handshake

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM3EnginePerfTest.java
Add a benchmark for BouncyCastle SM3 engine, exactly `org.bouncycastle.crypto.digests.SM3Digest`, to JMH test SM3MessageDigestPerfTest.
This PR will resolve #216.
=> TKSS-216: Add JMH benchmark for BouncyCastle SM3 engine

.github/workflows/gradle-build.yaml
It looks GitHub has no enough macOS platforms for running actions.
This problem may block a PR testing for a long time.
This PR will resolve #228.
=> TKSS-228: Remove macOS from GitHub actions

kona-crypto/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS8Key.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/X509Key.java
This is a backport of [JDK-8308010]: X509Key and PKCS8Key allows garbage bytes at the end.
This PR will resolve #242.
[JDK-8308010]:
<https://bugs.openjdk.org/browse/JDK-8308010>
=> TKSS-242: Backport JDK-8308010: X509Key and PKCS8Key allows garbage bytes at the end

kona-crypto/src/main/java/com/tencent/kona/sun/security/action/GetPropertyAction.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/OCSP.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/URICertStore.java
This is a backport of [JDK-8179502]: Enhance OCSP, CRL and Certificate Fetch Timeouts.
This PR will resolve #243.
[JDK-8179502]:
<https://bugs.openjdk.org/browse/JDK-8179502>
=> Backport JDK-8179502: Enhance OCSP, CRL and Certificate Fetch Timeouts

kona-crypto/src/main/java/com/tencent/kona/jdk/internal/misc/SharedSecretsUtil.java
The system property `useSharedSecrets` could be `true` by default on JDK 8.
This PR will resolve #252.
=> TKSS-252: Enable useSharedSecrets by default on JDK 8

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/NamedGroup.java
The [patch] for `TKSS-110: Backport JDK-8281236: (D)TLS key exchange named groups` changes the system property `com.tencent.kona.ssl.namedGroups` to `jdk.tls.namedGroups` accidentally.
This PR will resolve #258.
[patch]:
<https://github.com/Tencent/TencentKonaSMSuite/commit/dd1cfec74d7053da5c1d327f8ff19d7901ad84a1>
=> TKSS-258: Use system property name com.tencent.kona.ssl.namedGroups rather than jdk.tls.namedGroups

buildSrc/src/main/kotlin/kona-common.gradle.kts
com.tencent.kona.ssl.misc.SysPropNamedGroupsTest failed on Windows due to the below error,
```
---------- Server log start ----------
Error: Could not find or load main class com.tencent.kona.ssl.interop.JdkProcServer
---------- Server log end  ----------
```
It would ignore this test on Windows.
This PR will resolve #266.
=> TKSS-266: SysPropNamedGroupsTest failed on Windows

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateAuthoritiesExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateRequest.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificateRequest.java
This is a backport of [JDK-8294985]: SSLEngine throws IAE during parsing of X500Principal.
This PR will resolve #268.
[JDK-8294985]:
<https://bugs.openjdk.org/browse/JDK-8294985>
=> TKSS-268: Backport JDK-8294985: SSLEngine throws IAE during parsing of X500Principal

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLHandshake.java
This is a backport of [JDK-8310106]: sun.security.ssl.SSLHandshake.getHandshakeProducer() incorrectly checks handshakeConsumers.
This PR will resolve #269.
[JDK-8310106]:
<https://bugs.openjdk.org/browse/JDK-8310106>
=> TKSS-269: Backport JDK-8310106: sun.security.ssl.SSLHandshake.getHandshakeProducer() incorrectly checks handshakeConsumers

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerInputStream.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerOutputStream.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerValue.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS9Attribute.java
This is a backport of [JDK-8279254]: PKCS9Attribute SigningTime always encoded in UTFTime.
This PR will resolve #270.
[JDK-8279254]:
<https://bugs.openjdk.org/browse/JDK-8279254>
=> TKSS-270: Backport JDK-8279254: PKCS9Attribute SigningTime always encoded in UTFTime

kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
KeyToolTest should allow to specify different signature algorithms for generating certificates.
This PR will resolve #277.
=> TKSS-277: KeyToolTest::genCert should use different signature algorithms

kona-pkix/src/test/java/com/tencent/kona/pkix/provider/KeyStoreTest.java
Add some tests for loading encrypted private key directly.
These tests are only applicable to PKCS12 key store.
This PR will resolve #282.
=> TKSS-282: KeyStoreTest should test loading encrypted private key

kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBES2Parameters.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java, kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java, kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
KeyTool should support PBEWithHmacSM3AndSM4 on encrypting key store and private key.
This change only affects PKCS12 key store, since JKS key store uses non-PBE algorithm.
This PR will resolve #284.
=> TKSS-284: KeyTool supports PBEWithHmacSM3AndSM4

README.md, README_cn.md, kona-pkix/README.md, kona-pkix/README_cn.md
The READMEs should introduce that KeyTool supports PBEWithHmacSM3AndSM4 for encrypting private keys and store files.
This PR will resolve #286.
=> TKSS-286: Update READMEs on KeyTool supports PBEWithHmacSM3AndSM4

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateRequest.java
This is a backport of [JDK-8295068]: SSLEngine throws NPE parsing CertificateRequests.
This PR will resolve #288.
[JDK-8295068]:
<https://bugs.openjdk.org/browse/JDK-8295068>
=> TKSS-288: Backport JDK-8295068: SSLEngine throws NPE parsing CertificateRequests

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3Engine.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3MessageDigest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
The JDK MessageDigest implementations (see `sun.security.provider.DigestBase`) implement `Cloneable`.
So, `SM3MessageDigest` would also follow this routine.
This PR will resolve #291.
=> TKSS-291: SM3MessageDigest should be cloneable

kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/AlgorithmId.java
This is a backport of [JDK-8308398]: Move SunEC crypto provider into java.base.
The changes from JDK-8308398 just affects a bit of comments in `com.tencent.kona.sun.security.x509.AlgorithmId`.
This PR will resolve #294.
[JDK-8308398]:
<https://bugs.openjdk.org/browse/JDK-8308398>
=> TKSS-294: Backport JDK-8308398: Move SunEC crypto provider into java.base

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBES2Core.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBKDF2KeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/crypto/util/Sweeper.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/PBEUtil.java
This is a backport of [JDK-8301553]: Support Password-Based Cryptography in SunPKCS11.
This PR will resolve #298.
[JDK-8301553]:
<https://bugs.openjdk.org/browse/JDK-8301553>
=> TKSS-298: Backport JDK-8301553: Support Password-Based Cryptography in SunPKCS11

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBKDF2KeyImpl.java
This is a backport of [JDK-8311902]: Concurrency regression in the PBKDF2 key impl of SunJCE provider.
This PR will resolve #299.
[JDK-8311902]:
<https://bugs.openjdk.org/browse/JDK-8311902>
=> TKSS-299: Backport JDK-8311902: Concurrency regression in the PBKDF2 key impl of SunJCE provider

kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPadding.java
This is backport of [JDK-8309867]: redundant class field RSAPadding.md.
This PR will resolve #305.
[JDK-8309867]:
<https://bugs.openjdk.org/browse/JDK-8309867>
=> TKSS-305: Backport JDK-8309867: redundant class field RSAPadding.md

kona-crypto/src/main/java/com/tencent/kona/sun/security/action/GetPropertyAction.java
This is a backport [JDK-8312443]: sun.security should use toLowerCase(Locale.ROOT).
This PR will resolve #306.
[JDK-8312443]:
<https://bugs.openjdk.org/browse/JDK-8312443>
=> TKSS-306: Backport JDK-8312443: sun.security should use toLowerCase(Locale.ROOT)

kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkHttpsClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcUtils.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/Provider.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/Utilities.java
Currently, JDK peers support Kona-family providers only.
However, it should also support the OpenJDK-family providers, say SunJSSE.
This PR will resolve #310.
=> TKSS-310: JDK peers should support different providers

kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/Utilities.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/KonaServerSunJSSEClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SunJSSEServerKonaClientTest.java
Now that KonaSSL supports TLS 1.2 and 1.3 as well, it would add interop tests between it and SunJSSE on these protocols.
This PR will resolves #314.
=> TKSS-314: Add interop tests between KonaSSL and SunJSSE

kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlcpHandshakePerfTest.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlsHandshakePerfTest.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/SunJSSETlsHandshakePerfTest.java
Issue #310 (PR #311) refactored [java/com/tencent/kona/ssl/interop/Utilities.java], but the TLS JMH tests didn't modified accordingly.
This PR will resolve #316.
[java/com/tencent/kona/ssl/interop/Utilities.java]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/5a5da3efa9045a0da887aeccc2bd1621a7aa08c6/kona-ssl/src/test/java/com/tencent/kona/ssl/interop/Utilities.java>
=> TKSS-316: TLS JMH tests meet compilation error

kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/KeyStoreUtil.java
`KeyStoreUtil::getKeyStore` loads keystore from `InputStream`, but it doesn't release the resource after loading.
This PR will resolve #319.
=> TKSS-319: KeyStoreUtil::getKeyStore should release resource

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X400Address.java
This is a backport of [JDK-8312578:] Redundant javadoc in X400Address.
This PR will resolve #318.
[JDK-8312578:]:
<https://bugs.openjdk.org/browse/JDK-8312578>
=> TKSS-318: Backport JDK-8312578: Redundant javadoc in X400Address

kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/AbstractCalendar.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/BaseCalendar.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/CalendarDate.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/CalendarSystem.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/CalendarUtils.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/Era.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/ImmutableGregorianDate.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/LocalGregorianCalendar.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/ZoneInfo.java, kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/ZoneInfoFile.java
This is a backport of [JDK-6453901]: (cal) clean up sun.util.calendar classes.
This. PR will resolve #322.
[JDK-6453901]:
<https://bugs.openjdk.org/browse/JDK-6453901>
=> TKSS-322: Backport JDK-6453901: (cal) clean up sun.util.calendar classes

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java
This is a backport of [JDK-8311592]: ECKeySizeParameterSpec causes too many exceptions on third party providers.
This PR will resolve #324.
[JDK-8311592]:
<https://bugs.openjdk.org/browse/JDK-8311592>
=> TKSS-324: Backport JDK-8311592: ECKeySizeParameterSpec causes too many exceptions on third party providers

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerValue.java
This is a backport of [JDK-8313087]: DerValue::toString should output a hex view of the values in byte array.
This PR will resolve #326.
[JDK-8313087]:
<https://bugs.openjdk.org/browse/JDK-8313087>
=> TKSS-326: Backport JDK-8313087: DerValue::toString should output a hex view of the values in byte array

kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPadding.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSASignature.java
This is a backport of [JDK-8302017]: Allocate BadPaddingException only if it will be thrown.
This PR will resolve #329.
[JDK-8302017]:
<https://bugs.openjdk.org/browse/JDK-8302017>
=> TKSS-329: Backport JDK-8302017: Allocate BadPaddingException only if it will be thrown

kona-crypto/src/main/java/com/tencent/kona/sun/util/calendar/ZoneInfoFile.java
This is a backport of [JDK-8313231]: Redundant if statement in ZoneInfoFile.
This PR will resolve #331.
[JDK-8313231]:
<https://bugs.openjdk.org/browse/JDK-8313231>
=> TKSS-331: Backport JDK-8313231: Redundant if statement in ZoneInfoFile

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CRLImpl.java
This is a backport of [JDK-8313226]: Redundant condition test in X509CRLImpl.
This PR will resolve #333.
[JDK-8313226]:
<https://bugs.openjdk.org/browse/JDK-8313226>
=> TKSS-333: Backport JDK-8313226: Redundant condition test in X509CRLImpl

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/StatusResponseManager.java
This is a backport of [JDK-8312259]: StatusResponseManager unused code clean up.
This PR will resolve #338.
[JDK-8312259]:
<https://bugs.openjdk.org/browse/JDK-8312259>
=> TKSS-338: Backport JDK-8312259: StatusResponseManager unused code clean up

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java
This is a backport of [JDK-8314045]: ArithmeticException in GaloisCounterMode.
This PR will resolve #339.
[JDK-8314045]:
<https://bugs.openjdk.org/browse/JDK-8314045>
=> TKSS-339: Backport JDK-8314045: ArithmeticException in GaloisCounterMode

kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithTomcatDemo.java
```
public static class KonaSSLUtil extends SSLUtilBase {
-        private static final Log LOG = LogFactory.getLog(JSSEUtil.class);
+        private static final Log LOG = LogFactory.getLog(KonaSSLUtil.class);
```
This PR will resolve #345.
=> TKSS-345: TLSWithTomcatDemo misuses class for log

README.md, README_cn.md, kona-demo/README.md, kona-demo/README_cn.md
It would highlight the third-party components, such as `Jetty` and `Tomcat`, in the READMEs.
This PR will resolves #356.
=> TKSS-356: Highlight third-party components in README

kona-demo/build.gradle, kona-demo/src/main/java/com/tencent/kona/demo/TomcatServer.java
It is unnecessary to use the custom `Connector` for applying the custom `SSLImplementation`.
Instead, using `Connector` property `sslImplementationName` to apply that `SSLImplementation`.
This PR will resolves #358.
=> TKSS-358: TomcatServer would not use custom Connector

LICENSE.txt, README.md
It would remove BouncyCastle from LICENSE.txt due to TencentKonaSMSuite doesn't depend on it any more.
This PR will resolve #366.
=> TKSS-366: Remove BouncyCastle from LICENSE.txt

kona-crypto/src/main/java/com/tencent/kona/crypto/util/SM2Ciphertext.java, kona-crypto/src/test/java/com/tencent/kona/crypto/util/SM2CiphertextTest.java
The SM2 ciphertext formats could be plain `C1||C3||C2` or `C1||C2||C3`.
And the format of `C1` part, exactly public key point, should be `04||x||y`.
`04` means the point format is uncompressed, and `x` and `y` are the point coordinate.
Some implementations may miss the leading `04` for the above formats.
SM2Ciphertext should check this case for alerting the ciphertext is illegal.
This PR will resolves #368.
=> TKSS-368: SM2Ciphertext should check uncompressed flag

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLEngineOutputRecord.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSocketOutputRecord.java
TLCP is based on TLS 1.1 and TLS 1.2, so it has no chosen-plaintext issue on CBC mode ciphers.
This PR will resolves #371.
=> TKSS-371: No need to counter chosen-plaintext issue on TLCP

gradle/libs.versions.toml, kona-crypto/build.gradle.kts, kona-pkix/build.gradle.kts, kona-provider/build.gradle.kts, kona-ssl/build.gradle.kts
Gradle 8.3 complains that Gradle 9.0 will not load test framework implementation dependencies automatically.
So, it should declare junit-platform-launcher as runtime dependency explicitly.
This PR will resolve #377.
=> TKSS-377: Declare junit-platform-launcher as runtime dependency explicitly

.github/workflows/gradle-build.yaml, .github/workflows/scripts/precheck.sh
It would be better to check trailing whitespaces on PR.
This check must succeed before running Gradle jobs.
This PR will resolves #385.
=> TKSS-385: Add GitHub workflow job for checking trailing whitespaces

kona-ssl/build.gradle.kts
`jmhImplementation` --> `jmhAnnotationProcessor`.
=> TKSS-396: kona-ssl uses wrong function for JMH annotation processor

kona-crypto/README.md, kona-crypto/README_cn.md, kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM3HMacPerfTest.java, kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacWithBCTest.java
According to OpenJDK naming convention, it would be better to use `HmacSM3` as the standard name for SM3 HMAC.
And `SM3HMac` is an alias for this algorithm name.
=> TKSS-400: Use HmacSM3 as the standard name for SM3 HMAC algorithm

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3MessageDigest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
SM3MessageDigest must check the input to make sure it can get the valid byte array from the input.
This PR will resolve #402.
=> TKSS-402: SM3MessageDigest must check the input bounds

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
It should add test cases to `SM3Test` and `SM3HMacTest` for covering the APIs on ByteBuffer.
This PR will resolves #406.
=> TKSS-406: Add SM3 test cases with ByteBuffer

kona-crypto/src/main/java/com/tencent/kona/com/sun/crypto/provider/HmacCore.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
It would be better to add some SM3 test cases with empty and null inputs.
This PR will resolves #408.
=> TKSS-408: Add SM3 test cases with empty and null inputs

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java
```java
@Test
public void testNoInput() throws Exception {
...
Mac sm3HMac2 = Mac.getInstance("HmacSM3", PROVIDER);
sm3HMac2.init(keySpec);
sm3HMac1.update(new byte[0]);
byte[] mac2 = sm3HMac1.doFinal();
...
}
```
Here `sm3HMac1` must be `sm3HMac2`.
This PR will resolve #410.
=> TKSS-410: SM3HMacTest::testNoInput misuses Mac instance

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
As an algorithm independent of SM2, the test for SM4 should not rely on SM2.
This PR will resolves #414.
=> TKSS-414: SM4Test should not depend on SM2

kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM4KeySpec.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
It would be better to use SecretKeySpec(key, "SM4") instead of SM4KeySpec.
This PR will resolves #417.
=> TKSS-417: Deprecate SM4KeySpec

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLEngineImpl.java
This is a backport of [JDK-8293176]: SSLEngine handshaker does not send an alert after a bad parameters.
This PR will resolves #416.
[JDK-8293176]:
<https://bugs.openjdk.org/browse/JDK-8293176>
=> TKSS-416: Backport JDK-8293176: SSLEngine handshaker does not send an alert after a bad parameters

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Parameters.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParametersTest.java
If `SM4Parameters` instance is initiated via method `engineInit(AlgorithmParameterSpec paramSpec)`, and then `engineGetParameterSpec` will throws `NullPointerException`.
In the above case, the `encoded` is null, so the invocation on method `decode` must fail with `NullPointerException`.
However, it is unnecessary to try to decode the `iv`, since the `iv` is already there.
This PR will resolves #420.
=> TKSS-420: SM4Parameters::engineGetParameterSpec throws NullPointerException

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ServerNameExtension.java
This is a backport of [JDK-8301686]: TLS 1.3 handshake fails if server_name doesn't match resuming session.
This PR will resolve #424.
[JDK-8301686]:
<https://bugs.openjdk.org/browse/JDK-8301686>
=> TKSS-424: Backport JDK-8301686: TLS 1.3 handshake fails if server_name doesn't match resuming session

buildSrc/src/main/kotlin/kona-common.gradle.kts
After using Gradle toolchain, It would be better to print the JDK used by the test task.
This PR will resolves #431.
=> TKSS-431: Display testing JDK

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
This is a backport of [JDK-8309667]: TLS handshake fails because of ConcurrentModificationException in PKCS12KeyStore.engineGetEntry.
This PR will resolves #429.
[JDK-8309667]:
<https://bugs.openjdk.org/browse/JDK-8309667>
=> TKSS-429: Backport JDK-8309667: TLS handshake fails because of ConcurrentModificationException in PKCS12KeyStore.engineGetEntry

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS7.java
This is a backport of [JDK-8315042]: NPE in PKCS7.parseOldSignedData.
This PR will resolves #430.
[JDK-8315042]:
<https://bugs.openjdk.org/browse/JDK-8315042>
=> TKSS-430: Backport JDK-8315042: NPE in PKCS7.parseOldSignedData

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
When #99 backported [JDK-8297065], some changes in PKCS12KeyStore were missed.
This PR will resolves #436.
[JDK-8297065]:
<https://bugs.openjdk.org/browse/JDK-8297065>
=> TKSS-436: Re-backport JDK-8297065 for PKCS12KeyStore

kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2CipherTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2SignatureTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java, kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java, kona-ssl/src/test/java/com/tencent/kona/ssl/TestUtils.java, kona-ssl/src/test/java/com/tencent/kona/ssl/hybrid/JdkServerJdkClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerJdkClientTest.java
It should just use JUnit5 `Assertions::assertThrows` instead of custom method `TestUtils::checkThrowable`.
This PR will resolves #445.
=> TKSS-445: Use JUnit5 Assertions::assertThrows

kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2SignatureTest.java
It would not declare SM3withSM2 signature directly, instead, declare it as an alias of SM2 signature.
This PR will resolves #447.
=> TKSS-447: Declare SM3withSM2 as an alias of SM2 signature

kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2ParameterSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2SignatureParameterSpec.java
`SM2KeyAgreementParamSpec` and `SM2SignatureParameterSpec` are public APIs, so they would not depend on the internal `SM2PrivateKey` and `SM2PublicKey`.
This PR will resolves #449.
=> TKSS-449: AlgorithmParameterSpecs would not depend on internal Keys

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyAgreementTest.java
The fields in `SM2KeyAgreementParamSpec` should not be public.
It would access them via *getXXX* methods.
This PR will resolves #455.
=> TKSS-455: SM2KeyAgreementParamSpec should not expose fields directly

kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PrivateKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PublicKeySpec.java
`SM2PublicKeySpec` and `SM2PrivateKeySpec` do not need to copy a sub-array from a byte array as the keys.
It would be better to just accept the whole array.
This PR will resolves #457.
=> TKSS-457: SM2 KeySpecs should not copy a part of a byte array as keys

kona-crypto/src/main/java/com/tencent/kona/crypto/spec/RFC5915EncodedKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2ParameterSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PrivateKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PublicKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2SignatureParameterSpec.java
kona-crypto introduced a set of public APIs, like `SM2PublicKeySpec`, it would be better to add formal Javadocs for them.
This PR will resolves #453.
=> TKSS-453: Add Javadocs for new public APIs

kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2CipherTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyAgreementTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2SignatureTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParametersTest.java
Generally, the applications, including tests, should not use provider-internal classes, say `SM2PrivateKey` and `SM2PublicKey`.
Instead, they should use only JDK public APIs, say `SM2PrivateKeySpec` and `SM2PublicKeySpec`.
This PR will resolves #452.
=> TKSS-452: Tests should not depend on provider-internal classes

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBEKey.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBKDF2KeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECPrivateKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECPublicKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPrivateCrtKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPrivateKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPublicKeyImpl.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/X509CertPath.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CertImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/provider/TlsMasterSecretGenerator.java
This is a backport of [JDK-8286503]: Enhance security classes.
This JBS issue should be a vulnerability issue, so it is not visible for public.
But this vulnerability issue looks have no CVE number.
This PR will resolves #463.
[JDK-8286503]:
<https://github.com/openjdk/jdk/commit/adca97b659d725b0dd320322297dcbd1b443a047>
=> TKSS-463: Backport JDK-8286503: Enhance security classes

kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/CertPathHelper.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/ForwardBuilder.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/ForwardState.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/SunCertPathBuilder.java
This is a backport of [JDK-8309966]: Enhanced TLS connections.
This JBS issue should be a vulnerability issue, so it is not visible for public.
This vulnerability issue looks have a CVE number, exactly CVE-2023-22081.
This PR will resolves #464.
[JDK-8309966]:
<https://github.com/openjdk/jdk/commit/7c80cb26dfb6e90147f5f36d780457eff09e58ad>
=> TKSS-464: Backport JDK-8309966: Enhanced TLS connections

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4EnginePerfTest.java
`SM4EnginePerfTest` would use `EngineHolder` instead of `EncrypterHolder`.
This PR will resolves #472.
=> TKSS-472: SM4EnginePerfTest would use EngineHolder

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherBlockChaining.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherCore.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherFeedback.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GHASH.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/OutputFeedback.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBEKeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBES2Parameters.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBKDF2KeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PKCS5Padding.java
This is a backport of [JDK-8315974]: Make fields final in 'com.sun.crypto.provider' package.
This PR will resolves #474.
[JDK-8315974]:
<https://bugs.openjdk.org/browse/JDK-8315974>
=> TKSS-474: Backport JDK-8315974: Make fields final in 'com.sun.crypto.provider' package

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyFactory.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyFactoryTest.java
It has to re-work `SM2KeyFactory` for complying with JCA design principles.
This PR will resolves #477.
=> TKSS-477: SM2KeyFactory needs to be compliant with JCA style

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyPairGenerator.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyPairGeneratorTest.java
`SM2KeyPairGenerator` must declare that only `SM2ParameterSpec` or `NamedCurve` (`curveSM2`), but not general `ECParameterSpec`, is supported.
This PR will resolves #479.
=> TKSS-479: SM2KeyPairGenerator must declare only SM2ParameterSpec is supported

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java, kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/SM2Operations.java
In JDK, the infinite point on ECC is `(null, null)`, not `(0, 0)`.
This PR will resolves #481.
=> TKSS-481: EC infinite point is not (0, 0)

kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3MessageDigest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2CipherTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2SignatureTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
It would be better to add test cases for algorithm aliases, like `SM3Hmac` or `OID.1.2.156.10197.1.301`.
=> TKSS-483: Add tests for algorithm aliases

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyPairGenerator.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyPairGeneratorTest.java
`SM2KeyPairGenerator::initialize` should raise `IllegalArgumentException` even if the `params` is null.
This PR will resolves #486.
=> TKSS-486: SM2KeyPairGenerator::initialize should not raise NullPointerException

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyFactoryTest.java
It should check if the encoded SM2 public key starts with `0x04`.
This PR will resolves #493.
=> TKSS-493: SM2 public key should start with 0x04

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperator.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2CipherTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2SignatureTest.java, kona-crypto/src/test/java/com/tencent/kona/sun/security/ec/ECOperatorTest.java
ECOperator should use `ECPoint.POINT_INFINITY` rather than self-defined `ECPoint(0, 0)` as infinite point.
This PR will resolves #494.
=> TKSS-494: ECOperator should use ECPoint.POINT_INFINITY as infinite point

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4KeyGenerator.java
The field `keySize` in `SM4KeyGenerator` looks unnecessary due to SM4 key always be 16-bytes.
This PR will resolves #497.
=> TKSS-497: Unnecessary field keySize in SM4KeyGenerator

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java, kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java
`SM2Signature` should support only `engineSetParameter(AlgorithmParameterSpec params)`, and remove `engineSetParameter(String param, Object value)` and `engineGetParameter(String param)`.
This PR will resolves #499.
=> TKSS-499: SM2Signature should not set/get parameters via names

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/HmacPKCS12PBE_SM3.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Cipher.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyPairGenerator.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2PrivateKey.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2PublicKey.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3HMac.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3HMacKeyGenerator.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Crypt.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4GenParameterSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4ParameterGenerator.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/RFC5915EncodedKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2ParameterSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PrivateKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PublicKeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2SignatureParameterSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM4KeySpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java, kona-crypto/src/main/java/com/tencent/kona/crypto/util/SM2Ciphertext.java
The new introduced provider-internal and public `AlgorithmParameterSpec` classes should be final.
This PR will resolves #502.
=> TKSS-502: Provider-internal and public spec classes should be final

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyAgreementTest.java
A `SM2KeyAgreement` instance can be reused after re-init it.
This PR will resolves #505.
=> TKSS-505: SM2KeyAgreement instance should allow to be reused after re-init

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/SM2Operations.java
SM2 private key range would be better in `[1, order - 2]` instead of `[1, order - 1]`, though the possibility of hitting `order - 1` is quite low.
This PR will resolves #510.
=> TKSS-510: SM2 private key would not be order - 1

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParametersTest.java
`SM4ParametersTest` would specify the provider `KonaCrypto` explicitly.
This PR will resolves #513.
=> TKSS-513: SM4ParametersTest should specify the provider

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4KeyGeneratorTest.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/keytool/Main.java
This is a backport of [JDK-8316964]: Security tools should not call System.exit.
This PR will resolves #512.
[JDK-8316964]:
<https://bugs.openjdk.org/browse/JDK-8316964>
=> TKSS-512: Backport JDK-8316964: Security tools should not call System.exit

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyPairGenerator.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3HMacKeyGenerator.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4KeyGenerator.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4ParameterGenerator.java
`kona-crypto` would use the shared `SecureRandom` via `JCAUtil::getSecureRandom` instead of `new SecureRandom()`.
This PR will resolves #515.
=> TKSS-515: kona-crypto should use JCAUtil::getSecureRandom

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/ECKeyPairGeneratorTest.java
Add some test cases for using `ECKeyPairGenerator` to generate EC key pairs on SM2 curve.
This PR will resolve #524.
=> TKSS-524: Add test for ECKeyPairGenerator on SM2 curve

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2SignatureParameterSpec.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyAgreementTest.java
`SM2KeyAgreementParamSpec` should check if the IDs are longer than 8192-bytes.
This PR will resolves #530.
=> TKSS-530: SM2KeyAgreementParamSpec should check ID length

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/ECKeyPairGeneratorTest.java
Adds some cases checking if the key pairs generated by `ECKeyPairGenerator` can be used for SM2 cipher, signature and key agreement.
This PR will resolves #537.
=> TKSS-537: Test SM2 cipher, signature and key agreement with ECKeyPairGenerator

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/ECOperatorPerfTest.java
`ECOperatorPerfTest ` needs to use `ECOperations` rather than `SM2Operations`.
This PR will resolves #539.
=> TKSS-539: ECOperatorPerfTest needs to use ECOperations

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateMessage.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLConfiguration.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificate.java
This is a backport of [JDK-8311596]: Add separate system properties for TLS server and client for maximum chain length.
This PR will resolves #534.
[JDK-8311596]:
<https://bugs.openjdk.org/browse/JDK-8311596>
=> TKSS-534: Backport JDK-8311596: Add separate system properties for TLS server and client for maximum chain length

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/DNSName.java
This is a backport of [JDK-8311546]: Certificate name constraints improperly validated with leading period.
This PR will resolves #535.
[JDK-8311546]:
<https://bugs.openjdk.org/browse/JDK-8311546>
=> TKSS-535: Backport JDK-8311546: Certificate name constraints improperly validated with leading period

kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2ParameterSpec.java, kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2SignatureParameterSpec.java
Although most of public methods in parameter spec classes have Javadoc, some getter methods miss it.
This PR will resolves #544.
=> TKSS-544: Some parameter spec public methods miss Javadoc

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoInsts.java, kona-pkix/src/main/java/com/tencent/kona/pkix/PKIXUtils.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/CertificateFactoryTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/KeyFactoryTest.java
`KonaCrypto` would remove the support on `RSA` and `RSASSA-PSS`.
This PR will resolves #548.
=> TKSS-548: KonaCrypto should not support RSA and RSASSA-PSS

kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
`KeyTool` provides option `-file` for exporting certificate to local file, so `KeyToolTest` should use this option rather than redirecting the stdout to the local file.
This PR will resolves #550.
=> TKSS-550: KeyToolTest should export certificate to file with option -file

kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
`KeyToolTest` would directly run `keytool.Main::main` instead of running `KeyTool` in sub process.
This way is friendly for debugging.
This PR will resolves #555.
=> TKSS-555: KeyToolTest would not use sub process

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLConfiguration.java
This is a backport of [JDK-8319670]: Improve comments describing system properties for TLS server and client for max chain length.
This PR will resolves #557.
[JDK-8319670]:
<https://bugs.openjdk.org/browse/JDK-8319670>
=> TKSS-557: Backport JDK-8319670: Improve comments describing system properties for TLS server and client for max chain length

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CertImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateVerify.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EClientKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EServerKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2ServerKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificateVerify.java
It would not to invoke `Constants::defaultId` to get the default ID, instead, directly use the ID value,
`new byte[] { 49, 50, 51, 52, 53, 54, 55, 56, 49, 50, 51, 52, 53, 54, 55, 56}`
This PR will resolves #560.
=> TKSS-560: Use default ID value directly

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoInsts.java
`CryptoInsts::getKeyFactory` should return the `ECKeyFactory` implementation from provide `KonaCrypto`.
#548 introduced this change.
This PR will resolves #564.
=> TKSS-564: CryptoInsts::getKeyFactory should return KonaCrypto ECKeyFactory

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs10/PKCS10.java
This is a backport of [JDK-8320049]: PKCS10 would not discard the cause when throw SignatureException on invalid key.
This PR will resolves #567.
[JDK-8320049]:
<https://bugs.openjdk.org/browse/JDK-8320049>
=> TKSS-567: Backport JDK-8320049: PKCS10 would not discard the cause when throw SignatureException on invalid key

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
`SM3Test` would add a case on reusing `SM3MessageDigest` instance.
This PR will resolves #577.
=> TKSS-577: SM3Test adds case on reusing MessageDigest instance

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
`SM4Test` would add some cases on reusing `SM4Cipher` instances.
This PR will resolves #581.
=> TKSS-581: SM4Test add cases on reusing Cipher instances

.github/workflows/build-pr.yml
It could add JDK 21 for the GitHub `setup-java` action.
This PR will resolves #583.
=> TKSS-583: GitHub CI covers JDK 21

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CipherSuite.java
`HashAlg` `H_SM3` in `CipherSuite` contains a redundant comma, like the below,
```
H_SM3       ("SM3",     32,  64),;
```
This PR will resolves #587.
=> TKSS-587: HashAlg contains a redundant comma

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/AEADBufferedStream.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java, kona-crypto/src/main/java/com/tencent/kona/jdk/internal/util/ArraysSupport.java
This is a backport of [JDK-8318756]: Create better internal buffer for AEADs.
This PR will resolves #586.
[JDK-8318756]:
<https://bugs.openjdk.org/browse/JDK-8318756>
=> TKSS-586: Backport JDK-8318756: Create better internal buffer for AEADs

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateVerify.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ProtocolVersion.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificateVerify.java
It would enhance passing `SM2SignatureParameterSpec` to signature scheme `sm2sig_sm3`.
`SignatureScheme` should handle the most of logics for this case.
This PR will resolves #594.
=> TKSS-594: Enhance passing SM2SignatureParameterSpec to sm2sig_sm3

kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs10/PKCS10.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/keytool/Main.java
This is a backport of [JDK-8202598]: keytool -certreq output contains inconsistent line separators.
This PR will resolves #596.
[JDK-8202598]:
<https://bugs.openjdk.org/browse/JDK-8202598>
=> TKSS-596: Backport JDK-8202598: keytool -certreq output contains inconsistent line separators

kona-crypto/src/main/java/com/tencent/kona/sun/security/jca/JCAUtil.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Debug.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/SignerInfo.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/BasicChecker.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/Builder.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/CertId.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/DistributionPointFetcher.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/ForwardBuilder.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/OCSPResponse.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/RevocationChecker.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/Vertex.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/util/SSLLogger.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/SerialNumber.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/StatusResponseManager.java
This is a backport of [JDK-8296787]: Unify debug printing format of X.509 cert serial numbers.
This PR will resolves #597.
[JDK-8296787]:
https://bugs.openjdk.org/browse/JDK-8296787
=> TKSS-597: Backport JDK-8296787: Unify debug printing format of X.509 cert serial numbers

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java
It is unnecessary to set `SM2SignatureParameterSpec` for `sm2sig_sm3` on pre-TLS 1.3 protocols.
This PR will resolves #602.
=> TKSS-602: No need to set SM2SignatureParameterSpec for sm2sig_sm3 on pre-TLS 1.3

gradle/libs.versions.toml
BouncyCastle 1.77 was released last month.
It would be better to upgrade the test dependency on this component.
This PR will resolves #601.
=> TKSS-601: Upgrade BouncyCastle to 1.77

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Utilities.java
`TLS13_SM_ID` is used by `SignatureScheme` only, so it is unnecessary to expose it.
This PR will resolves #604.
=> TKSS-604: TLS13_SM_ID would be private

kona-demo/src/main/java/com/tencent/kona/demo/TomcatServer.java, kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java, kona-pkix/src/test/java/com/tencent/kona/pkix/demo/PKIDemo.java, kona-pkix/src/test/java/com/tencent/kona/pkix/demo/SignatureDemo.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/CertPathBuilderTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/CertPathValidatorTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/CertStoreTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/CertificateFactoryTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/KeyFactoryTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/KeyStoreTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyStoreToolTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/TestUtils.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithGRPCDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithHttpClientDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithJettyDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithNettyDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithTomcatDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithoutCertValidationDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithGRPCDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithJettyDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithOkHttpDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithTomcatDemo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/SSLEngineTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/SSLSocketTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SSLSocketOnTLS12Test.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SSLSocketOnTLS13Test.java
`CryptoInsts`, `PKIXInsts` and `SSLInsts` are used by the implementations only.
The tests, especially demos, would not use them.
This PR will resolves #600.
=> TKSS-600: Test and demos would not use XXXInsts classes

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PKCS5Padding.java
This is a backport of [JDK-8322734]: A redundant return in method padWithLen.
This PR will resolves #612.
[JDK-8322734]:
https://bugs.openjdk.org/browse/JDK-8322734
=> TKSS-612: A redundant return in method padWithLen

kona-crypto/src/main/java/com/tencent/kona/sun/security/jca/JCAUtil.java, kona-pkix/build.gradle.kts, kona-pkix/src/jmh/java/com/tencent/kona/pkix/perf/KeyStorePerfTest.java
It would add a JMH test for `KeyStore`, especially on getting entries from `PKCS12KeyStore`.
This PR will resolves #613.
=> TKSS-613: Add JMH test for KeyStore

kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlsHandshakePerfTest.java
SM2 certificate and curve can be used in TLS 1.2, so `KonaSSLTlsHandshakePerfTest` would cover TLS 1.2 as well.
This PR will resolve #617.
=> TKSS-617: KonaSSLTlsHandshakePerfTest would cover TLS 1.2

kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/TlcpHandshakeProfTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/TlsHandshakeProfTest.java
Add tests for profiling TLS/TLCP handshaking with different parameters.
This PR will resolves #619.
=> TKSS-619: Add tests for profiling handshaking

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificate.java
The field `format` in enum `CertListFormat` should be `private` and  `final`.
This PR will resolve #621.
=> TKSS-621: CertListFormat.format should be private final

kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/provider/TlcpMasterSecretGenerator.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/provider/TlcpSM2PremasterSecretGenerator.java
KonaSSLProvider contains some aliases for TLCP KeyGenerators , like `TlcpKeyMaterial`.
However these aliases are not necessary.
This PR will resolves #623.
=> TKSS-623: Remove redundant aliases from KonaSSLProvider

kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthenticator.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPContextImpl.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/SSLSocketTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SSLSocketOnTLS13Test.java
OpenJDK has some aliases for PKIX trust manager and NewSunX509 key manager, so TKSS also needs to align to OpenJDK.
This PR will resolves #627.
=> TKSS-627: Add aliases for trust manager and key manager

kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
When load a new keystore, storeEntryCache should be cleared.
=> TKSS-629: PKCS12KeyStore should clear storeEntryCache

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLHandshake.java
Some `SSLHandshake` entries on TLCP are redundant.
This PR will resolves #634.
=> TKSS-634: Remove redundant entries on TLCP from SSLHandshake

kona-demo/src/main/java/com/tencent/kona/demo/AppConfig.java, kona-demo/src/main/java/com/tencent/kona/demo/JettyServer.java, kona-demo/src/main/resources/application.yml
It allows to config `JettyServer` to support client authentication.
This PR will resolves #637.
=> TKSS-637: JettyServer supports client authentication

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECDHKeyAgreement.java
This is a backport of [JDK-8320449]: ECDHKeyAgreement should validate parameters before using them.
This PR will resolves #639.
[JDK-8320449]:
https://bugs.openjdk.org/browse/JDK-8320449
=> TKSS-639: Backport JDK-8320449: ECDHKeyAgreement should validate parameters before using them

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBEKey.java
This is a backport of [JDK-8286503]: Enhance security classes.
This PR will resolves #641.
[JDK-8286503]:
https://github.com/openjdk/jdk21u/commit/8b7afecff14fcf695a6b0b9230c21e4b2e86f1dc
=> TKSS-641: Backport JDK-8286503: Enhance security classes

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificateRequest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/SSLSocketTest.java
Remove the codes not related to TLCP from TLCPCertificateRequest.
This PR will resolves #658.
=> TKSS-658: Simplify TLCPCertificateRequest

kona-pkix/src/main/java/com/tencent/kona/sun/security/validator/EndEntityChecker.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLMasterKeyDerivation.java
TLCP requires two certificates, exactly sign and enc certificates.
The sign certificate should always have `digitalSignature` key usage regardless of key exchange (`SM2` or `SM2E`).
It would be better to improve the checking on this certificate.
This PR will resolves #678.
=> TKSS-678: Better certificate key usage checking on TLCP

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EClientKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EServerKeyExchange.java
Generally, the classes in one provider should not invoke the classes in another provider.
So, `SM2EServerKeyExchange` and `SM2ClientKeyExchange` should not create `SM2PublicKey` instances directly.
Instead, they should use SM2 key factory to generate the public key.
This PR will resolves #681.
=> TKSS-681: SM2E key exchange should not call SM2PublicKey directly

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/ConstraintTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/NoConstraintTest.java
TLCP always works with `sm2sig_sm3` and `curveSM2` regardless of the constraints on the named groups and signature schemes.
This PR will resolves #686.
=> TKSS-686: TLCP should not be restricted by the named group and signature scheme constraints

kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerBabaSSLClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerJdkClientTest.java
Some TLCP interop tests misuse intermediate CA certs as root CA certs.
This PR will resolves #691.
=> TKSS-691: TLCP tests misuse CA certs

kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerJdkClientTest.java
Add some test cases for checking if the expected exceptions are thrown when the expected application protocol and server are not found.
This PR will resolves #690.
=> TKSS-690: Add negative cases for ALPN and SNI tests

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Alert.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateMessage.java
This is a backport of [JDK-8311644]: Server should not send bad_certificate alert when the client does not send any certificates.
This PR will resolves #680.
[JDK-8311644]:
https://bugs.openjdk.org/browse/JDK-8311644
=> TKSS-680: Backport JDK-8311644: Server should not send bad_certificate alert when the client does not send any certificates

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/SignatureUtil.java
This is a backport of [JDK-8325506]: Ensure randomness is only read from provided SecureRandom object.
This PR will resolves #693.
[JDK-8325506]:
https://bugs.openjdk.org/browse/JDK-8325506
=> TKSS-693: Backport JDK-8325506: Ensure randomness is only read from provided SecureRandom object

kona-demo/src/main/java/com/tencent/kona/demo/AppConfig.java, kona-demo/src/main/java/com/tencent/kona/demo/JettyServer.java
The providers can be null, then kona-demo just uses the default providers.
Generally, the default providers comes from JDK.
This PR will resolves #698.
=> TKSS-698: kona-demo should allow not to specify providers

kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java, kona-demo/src/main/resources/application.yml, kona-pkix/src/test/java/com/tencent/kona/pkix/provider/KeyStoreProfTest.java, kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerBabaSSLClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerJdkClientTest.java
Some Tencent files were already updated in 2024, but the years in the copyright notes were not updated accordingly.
This PR will resolves #701.
=> TKSS-701: Update years in copyright notes

kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java
`TlcpKeyMaterialGenerator` was already removed by #706, then `KonaSSLProvider` should not define a entry for it.
This PR will resolves #708.
=> TKSS-708: KonaSSLProvider should not define TlcpKeyMaterial

kona-ssl/src/main/java/com/tencent/kona/ssl/SSLInsts.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/internal/spec/TlsKeyMaterialParameterSpec.java
Classes `TlcpKeyMaterial`, `TlcpMasterSecret` and `TlcpPrf` are already removed, but the names still present in classes `SSLInsts` and `TlsKeyMaterialParameterSpec`.
This PR will resolves #714.
=> TKSS-714: Remove unused TlcpKeyMaterial, TlcpMasterSecret and TlcpPrf

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Authenticator.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLTrafficKeyDerivation.java
Just use `T12TrafficKeyDerivationGenerator` instead of `TLCP11TrafficKeyDerivationGenerator`.
This PR will resolves #716.
=> TKSS-716: Remove TLCP11TrafficKeyDerivationGenerator

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java
`SM2` and `SM2E` in `TLCPAuthentication` are the same, so it could remove one.
This PR will resolves #719.
=> TKSS-719: Remove TLCPAuthentication SM2E

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/X509Authentication.java
This is a backport of [JDK-8312383]: Log X509ExtendedKeyManager implementation class name in TLS/SSL connection.
This PR will resolves #710.
[JDK-8312383]:
https://bugs.openjdk.org/browse/JDK-8312383
=> TKSS-710: Backport JDK-8312383: Log X509ExtendedKeyManager implementation class name in TLS/SSL connection

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Finished.java
`TLCP11` in `VerifyDataScheme` is not used anymore, so just remove it.
This PR will resolves #722.
=> TKSS-722: Remove unused VerifyDataScheme TLCP11

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLMasterKeyDerivation.java
It could not need `TLCP11` in `SSLMasterKeyDerivation`, instead, just use `TLS12` namely `kdf_tls12`.
This PR will resolves #724.
=> TKSS-724: Remove SSLMasterKeyDerivation TLCP11

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECKeyPairGenerator.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/ECUtil.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java
This is a backport of [JDK-8325164]: Named groups and signature schemes unavailable with SunPKCS11 in FIPS mode.
This PR will resolves #729.
[JDK-8325164]:
https://bugs.openjdk.org/browse/JDK-8325164
=> TKSS-729: Backport JDK-8325164: Named groups and signature schemes unavailable with SunPKCS11 in FIPS mode

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java, kona-crypto/src/main/java/com/tencent/kona/jdk/internal/misc/SharedSecretsUtil.java, kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java
SharedSecretsUtil doesn't support JDK 21 currently, however this JDK version should be supported.
This PR will resolves #730.
=> TKSS-730: SharedSecretsUtil should support JDK 21

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/X509Authentication.java
This is backport of [JDK-8327182]: Move serverAlias into the loop.
This PR will resolves #731.
[JDK-8327182]:
https://bugs.openjdk.org/browse/JDK-8327182
=> TKSS-731: Backport JDK-8327182: Move serverAlias into the loop

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2ServerKeyExchange.java
The method `SM2ServerKeyExchange::messageLength` contains a redundant semicolon.
This PR will resolves #736.
=> TKSS-736: Redundant semicolon in SM2ServerKeyExchange::messageLength

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java, kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java
`Constants` and `CryptoUtils` depend on in mutual. The former could not depend on the latter.
This PR will resolves #738.
=> TKSS-738: Constants should not depend on CryptoUtils

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerValue.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS7.java
`DerValue` and `PKCS7` have redundant semicolons.
This PR will resolves #741.
=> TKSS-741: Remove redundant semicolons from DerValue and PKCS7

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ServerHello.java
This is a backport of [JDK-8326643]: JDK server does not send a dummy change_cipher_spec record after HelloRetryRequest message.
[JDK-8326643]:
https://bugs.openjdk.org/browse/JDK-8326643
=> TKSS-739: Backport JDK-8326643: JDK server does not send a dummy change_cipher_spec record after HelloRetryRequest message

buildSrc/src/main/kotlin/kona-common.gradle.kts, kona-crypto/src/main/java/com/tencent/kona/jdk/internal/misc/SharedSecretsUtil.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcUtils.java
Different JDK releases, even minor releases, support different internal `Access` classes and methods.
`SharedSecretsUtil` should deal with this problem.
This PR will resolves #745.
=> TKSS-745: SharedSecretsUtil is not flexible

kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithNettyDemo.java
TLCPWithNettyDemo currently uses Jetty server, but it would be better to use Netty server.
This PR will resolves #750.
=> TKSS-750: TLCPWithNettyDemo should not use Jetty as server side

kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECPublicKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/x509/X509Key.java
This is a backport of [JDK-8327779]: Remove deprecated internal field sun.security.x509.X509Key.key.
This PR will resolves #752.
[JDK-8327779]:
https://bugs.openjdk.org/browse/JDK-8327779
=> TKSS-752: Backport JDK-8327779: Remove deprecated internal field sun.security.x509.X509Key.key

kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPrivateCrtKeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPrivateKeyImpl.java
This is a backport of [JDK-8318340]: Improve RSA key implementations.
This PR will resolves #764.
[JDK-8318340]:
https://github.com/openjdk/jdk8u/commit/54419d4dcd230a1c7bd9fc67a169c6ad6cb71385
=> TKSS-764: Backport JDK-8318340: Improve RSA key implementations

kona-pkix/src/main/java/com/tencent/kona/pkix/tool/KeyStoreTool.java
The option `keyPasswd` may confuse users, so it would be better to clarify a bit.
This PR will resolves #771.
=> TKSS-771: Improve KeyStoreTool usage hint

gradle/libs.versions.toml
BouncyCastle 1.78 just was released.
It would be better to use this version for testing.
This PR will resolves #773.
=> TKSS-773: Upgrade BouncyCastle to 1.78

buildSrc/src/main/kotlin/kona-common.gradle.kts
Adoptium Temurin JDK doesn't provide version 8 on macOS aarch64, so Gradle toolchain cannot use this JDK 8 on this platform.
This PR will resolves #779.
=> TKSS-779: Use any JDK 8 distro for compiling source

buildSrc/src/main/kotlin/CommonTest.kt, kona-pkix/src/test/resources/gen_certs.sh, kona-pkix/src/test/resources/gen_hybrid_certs.sh, kona-pkix/src/test/resources/gen_tlcp_certs.sh, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificate.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/OpenSSL.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/Tongsuo.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/TongsuoClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/TongsuoServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/TongsuoUtils.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerTongsuoClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/TongsuoServerJdkClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/JdkServerTongsuoClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/TongsuoServerJdkClientTest.java, kona-ssl/src/test/resources/gen_certs.sh, kona-ssl/src/test/resources/gen_hybrid_certs.sh, kona-ssl/src/test/resources/gen_tlcp_certs.sh
BabaSSL is already deprecated, so it would be better to use Tongsuo.
This PR will resolves #777.
=> TKSS-777: SSL tests use Tongsuo rather than BabaSSL

kona-ssl/src/test/java/com/tencent/kona/ssl/peers/SunJSSEClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/peers/SunJSSEServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/peers/TLCPClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/peers/TLCPServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/peers/TLSClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/peers/TLSServer.java
The peers in package `com.tencent.kona.ssl.peers` would support session resumption.
This PR will resolves #788.
=> TKSS-788: SSL peers support session resumption

kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkHttpsClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcUtils.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/Utilities.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/JdkServerJdkClientTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/tls/JdkServerTongsuoClientTest.java
It would not hard-code the key store type, trust and key manager algorithms.
Instead, just use the defaults.
This PR will resolves #791.
=> TKSS-791: Tests use the default key store type, trust and key manager algorithms

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ClientHello.java
This is a backport of [JDK-8332524]: Instead of printing "TLSv1.3," it is showing "TLS13".
[JDK-8332524]:
https://bugs.openjdk.org/browse/JDK-8332524
=> TKSS-796: Backport JDK-8332524: Instead of printing "TLSv1.3," it is showing "TLS13"

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/Curve25519OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/Curve448OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial25519.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial448.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialModBinP.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP256.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP384.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP521.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialSM2.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/MontgomeryIntegerPolynomialP256.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P256OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P384OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P521OrderField.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/SM2OrderField.java, kona-crypto/src/test/java/com/tencent/kona/sun/security/util/math/intpoly/FieldGen.java
This is a backport of [JDK-8333583]: Crypto-XDH.generateSecret regression after JDK-8329538.
This PR will resolves #800.
[JDK-8333583]:
https://bugs.openjdk.org/browse/JDK-8333583
=> TKSS-800: Backport JDK-8333583: Crypto-XDH.generateSecret regression after JDK-8329538

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSocketOutputRecord.java
This a backport of [JDK-8334670]: SSLSocketOutputRecord buffer miscalculation.
This PR will resolves #798.
[JDK-8334670]:
https://bugs.openjdk.org/browse/JDK-8334670
=> TKSS-798: Backport JDK-8334670: SSLSocketOutputRecord buffer miscalculation

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EKeyExchange.java
`SM2EPossession` should use the provided secure random via the constructor for initializing `KeyPairGenerator`.
This PR will resolves #806.
=> TKSS-806: SM2EPossession should use the provided secure random

kona-ssl/src/main/java/com/tencent/kona/ssl/SSLUtils.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ECDHKeyExchange.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EKeyExchange.java
`KeyPairGenerator.getInstance("SM2")` is unnecessary due to `KeyPairGenerator.getInstance("EC")` with curve `curveSM` is already supported.
So, the method `SSLUtils::getECKeyPairGenerator` could be removed.
This PR will resolves #808.
=> TKSS-808: Remove SSLUtils::getECKeyPairGenerator

kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java, kona-ssl/src/main/java/com/tencent/kona/ssl/SSLInsts.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2KeyExchange.java
Should define key generator `SunTls12RsaPremasterSecret`/`SunTlsRsaPremasterSecret` instead of `TlsRsaPremasterSecret`.
This PR will resolves #810.
=> TKSS-810: Remove key generator TlsRsaPremasterSecret

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificate.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPKeyAgreement.java
Align TLCP codes with the corresponding codes in JDK.
This PR will resolves #812.
=> TKSS-812: Cleanup TLCP codes

kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/SSLEngineTest.java
Set system property `com.tencent.kona.ssl.debug` for logging ssl, but uncomment it by default.
This PR will resolves #816.
=> TKSS-816: SSLEngineTest prints ssl logs

kona-crypto/src/main/java/com/tencent/kona/com/sun/crypto/provider/HmacCore.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherBlockChaining.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherCore.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherTextStealing.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/ConstructKeys.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/ElectronicCodeBook.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/FeedbackCipher.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GCTR.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GHASH.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/OutputFeedback.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBEKeyFactory.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBES2Parameters.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBKDF2KeyImpl.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PKCS5Padding.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/provider/TlsKeyMaterialGenerator.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/provider/TlsPrfGenerator.java
This is a backport of [JDK-8333364]: Minor cleanup could be done in com.sun.crypto.provider.
This PR will resolves #789.
[JDK-8333364]:
https://bugs.openjdk.org/browse/JDK-8333364
=> TKSS-789: Backport JDK-8333364: Minor cleanup could be done in com.sun.crypto.provider

.github/workflows/build-pr.yml
`gradle-build-action` version 3 has been released for a while, and the new major version is recommended by GitHub officially.
This PR will resolves #820.
=> TKSS-820: Upgrade gradle-build-action to version 3

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLExtension.java
This is a backport of [JDK-8327538]: The SSLExtension class specifies incorrect values for heartbeat per RFC 6520 and post_handshake_auth per RFC 8446.
This PR will resolves #829.
[JDK-8327538]:
https://bugs.openjdk.org/browse/JDK-8327538
=> TKSS-829: Backport JDK-8327538: The SSLExtension class specifies incorrect values for heartbeat per RFC 6520 and post_handshake_auth per RFC 8446

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/ECParameters.java
This is a backport of [JDK-8322133]: getParameterSpec(ECGenParameterSpec.class) on EC AlgorithmParameters does not return standard names.
This PR will resolves #832.
[JDK-8322133]:
https://bugs.openjdk.org/browse/JDK-8322133
=> TKSS-832: Backport JDK-8322133: getParameterSpec(ECGenParameterSpec.class) on EC AlgorithmParameters does not return standard names

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerInputStream.java
This is a backport of [JDK-8336667]: IAE in DerInputStream.toByteArray.
This PR will resolves #835.
[JDK-8336667]:
https://bugs.openjdk.org/browse/JDK-8336667
=> TKSS-835: Backport JDK-8336667: IAE in DerInputStream.toByteArray

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/Cache.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Finished.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/NewSessionTicket.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/PreSharedKeyExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLConfiguration.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLEngineImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSessionContextImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSessionImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSocketImpl.java
This is a backport of [JDK-8328608]: Multiple NewSessionTicket support for TLS.
This PR will resolves #795.
[JDK-8328608]:
https://bugs.openjdk.org/browse/JDK-8328608
=> TKSS-795: Backport JDK-8328608: Multiple NewSessionTicket support for TLS

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM3HMacPerfTest.java
`SM3HMacPerfTest` should use BC SM3HMac for the second benchmark test.
This PR will resolves #848.
=> TKSS-848: SM3HMacPerfTest uses Kona SM3HMac twice

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java
Compare with `SM3Test`, `SM3HMacTest` should have cases on resetting and reusing the `SM3HMac` instance as well.
This PR will resolves #850.
=> TKSS-850: Add reset and reuse test cases for SM3HMac

buildSrc/src/main/kotlin/kona-common.gradle.kts
Since version 8.6, Gradle has support Kona JDKs.
It should add Kona releases for testing.
This PR will resolves #854.
=> TKSS-854: Supports Kona JDKs

README.md, README_cn.md
Kona JDK 21 has been published, so the README should be updated for this change.
This PR will resolves #856.
=> TKSS-856: Update README for Kona JDK 21

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4DecrypterPerfTest.java, kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4EncrypterPerfTest.java
`SM4EncrypterPerfTest` and `SM4DecrypterPerfTest` add JMH benchmarks for `SM4-ECB` cipher.
This PR will resolves #858.
=> TKSS-858: Add JMH benchmarks for SM4-ECB

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeCrypto.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM3Test.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4EngineTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4Test.java
The method `NativeCrypto::loadLibs` should be private, and the tests don't call it anymore.
This PR will resolves #867.
=> TKSS-867: NativeCrypto::loadLibs should be private

kona-crypto/README.md, kona-crypto/README_cn.md, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeCrypto.java
OpenSSL 3.3.2 was published last month, so it would be better to update the OpenSSL binaries from 3.3.1 to this latest version.
This PR will resolves #874.
=> TKSS-874: Upgrade OpenSSL to version 3.3.2

kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/keytool/Main.java
This is a backport of [JDK-8339347]: keytool -importpass insists prompting the user even if there is no terminal.
This PR will resolves #881.
[JDK-8339347]:
https://bugs.openjdk.org/browse/JDK-8339347
=> TKSS-881: Backport JDK-8339347: keytool -importpass insists prompting the user even if there is no terminal

kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/keytool/Main.java
This is a backport of [JDK-8331391]: Enhance the keytool code by invoking the buildTrustedCerts method for essential options.
This PR will resolves #882.
[JDK-8331391]:
https://bugs.openjdk.org/browse/JDK-8331391
=> TKSS-882: Backport JDK-8331391: Enhance the keytool code by invoking the buildTrustedCerts method for essential options

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/PropertyExpander.java
This is a backport of [JDK-8319332]: Security properties files inclusion.
This PR will resolves #883.
[JDK-8319332]:
https://bugs.openjdk.org/browse/JDK-8319332
=> TKSS-883: Backport JDK-8319332: Security properties files inclusion

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/UntrustedCertificates.java
It is unnecessary to check if a certificate is blocked by JDK, so `UntrustedCertificates::isUntrusted` can always return `false`.
This PR will resolves #907.
=> TKSS-907: UntrustedCertificates::isUntrusted should return false

kona-crypto/README.md, kona-crypto/README_cn.md, kona-pkix/README.md, kona-pkix/README_cn.md, kona-provider/README.md, kona-provider/README_cn.md, kona-ssl/README.md, kona-ssl/README_cn.md
Generally, just need to add the Kona SM Suite providers to the bottom of the provider list.
So, it would not use `Security.insertProviderAt` to add the Kona SM Suite providers.
=> TKSS-911: Not recommend to prioritize the Kona SM Suite providers

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Engine.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2CipherTest.java
Refer to the SM2 cipher implementations from BouncyCastle and OpenSSL, this cipher would not encrypt empty message.
This PR will resolves #917.
=> TKSS-917: SM2 cipher would not encrypt empty message

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Engine.java
`SM2Engine:checkInputBound` should check if `len` rather `input.length` is greater than zero.
This PR will resolves #919.
=> TKSS-919: SM2Engine:checkInputBound should check len rather input.length

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2CipherPerfTest.java, kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2SignaturePerfTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java
Some SM2 JMH tests try to use `KonaCrypto` provider before register it.
This PR will resolves #921.
=> TKSS-921: SM2 JMH tests cannot find KonaCrypto provider

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLCipher.java
This is a backport of [JDK-8331682]: Slow networks/Impatient clients can potentially send unencrypted TLSv1.3 alerts that won't parse on the server.
This PR will resolves #926.
[JDK-8331682]:
https://bugs.openjdk.org/browse/JDK-8331682
=> TKSS-926: Backport JDK-8331682: Slow networks/Impatient clients can potentially send unencrypted TLSv1.3 alerts that won't parse on the server

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeRefProfTest.java
Add a test for profiling native crypto objects. For example, it can help checking memory leak.
This PR will resolves #948.
=> TKSS-948: Add a test for profiling native crypto objects

README.md, README_cn.md, kona-crypto/README.md, kona-crypto/README_cn.md
Now that provides OpenSSL-based SM2 implementations, the READMEs should be updated accordingly.
This PR will resolves #965.
=> TKSSp-965: Update READMEs for OpenSSL-based SM2 implementation

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/ByteArrayWriter.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2Cipher.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2Signature.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM3HMac.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM3MessageDigest.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Crypt.java
The native crypto implementations just be not thread-safe, so it's unnecessary to use `volatile` and `synchronized`.
This PR will resolves #973.
=> TKSS-973: No need to care thread-safe on native crypto

kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoInsts.java
Frequent `SM3` and `SM3HMac` JNI operations on small data are harmful for the TLCP session resumption performance.
This PR will resolves #979.
=> TKSS-979: TLCP session resumption performance regression with OpenSSL

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2KeyAgreementPerfTest.java
`SM2KeyAgreementPerfTest::setup` should be called for each invocation due to the public key is reset after generating key.
This PR will resolves #987.
=> TKSS-987: SM2KeyAgreementPerfTest should init for each invocation

.github/workflows/build-pr.yml, buildSrc/src/main/kotlin/kona-common.gradle.kts, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcClient.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcServer.java, kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkProcUtils.java
It should allow to run all unit tests on the native crypto provider.
It can provide an additional Gradle task to achieve that.
This PR will resolves #998.
=> TKSS-998: Run all unit tests on the native crypto provider

buildSrc/src/main/kotlin/kona-common.gradle.kts
It should allow to run PKIX and SSL JMH tests with the dual crypto providers respectively.
It can provide an additional Gradle task to achieve that.
This PR will resolves #1000.
=> TKSS-1000: Run PKIX and SSL JMH tests with the native crypto provider

kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlcpHandshakePerfTest.java
`KonaSSLTlcpHandshakePerfTest` currently uses cipher suite `TLCP_ECC_SM4_CBC_SM3`.
It should also cover `TLCP_ECDHE_SM4_CBC_SM3`.
This PR will resolves #1004.
=> TKSS-1004: KonaSSLTlcpHandshakePerfTest adds case on TLCP_ECDHE_SM4_CBC_SM3

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeMAC.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeRef.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2Cipher.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2KeyAgreement.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2KeyPairGen.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2Signature.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM3.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM3HMac.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4.java
Although the JNI/C functions check the pointers, it would also be better to check them on the Java layer.
If the pointer is 0, for example the native object is already closed, then it's unnecessary to call native methods.
This PR will resolves #1012.
=> TKSS-1002: Check pointer value

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2KeyAgreementPerfTest.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2KeyAgreement.java
`NativeSM2KeyAgreement` should be created in the constructor of `SM2KeyAgreement` instead of in the `engineInit` method.
This PR will resolves #1016.
=> TKSS-1016: NativeSM2KeyAgreement should be created in constructor

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Crypt.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
`NativeSM4.SM4GCM` instance has to be re-created if the initiation changes the opmode.
This PR will resolves #1022.
=> TKSS-1022: Need to re-create NativeSM4.SM4GCM instance when opmode is changed

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2SignatureConstantTimeTest.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2Signature.java
Native SM2Signature initialize should reset the parameters, like the private key and/or the public key, before set new values for them.
=> TKSS-1024: Native SM2Signature initialization should reset parameters at first

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4DecrypterPerfTest.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Crypt.java
`SM4DecrypterPerfTest` misses `KonaCrypto` provider.
=> TKSS-1026: SM4DecrypterPerfTest should cover KonaCrypto provider

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2Test.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM3HMacTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM3Test.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4Test.java
It should check the case closing a native crypto instance twice.
This PR will resolves #1030.
=> TKSS-1030: Add tests on closing a native crypto instance twice

README.md, README_cn.md
READMEs should be updated to add `KonaCrypto-Native` provider.
This PR will resolves #1032.
=> TKSS-1032: READMEs miss KonaCrypto-Native provider somewhere

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/AlgoCipher.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SymmetricCipher.java
The native `SymmetricCipher` interface should add method `updateAAD`, so that allows `AlgoCipher` not to cast `EmbeddedCipher` to a concrete implementation.
This PR will resolves #1034.
=> TKSS-1034: Native SymmetricCipher should add method updateAAD

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM3HMac.java
Native `SM3HMac::engineUpdate` should check parameters before copying the input.
This PR will resolves #1036.
=> TKSS-1036: Native SM3HMac engineUpdate should check parameters

kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoNativeProvider.java, kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlcpHandshakePerfTest.java
`KonaSSLTlcpHandshakePerfTest` would cover GCM cipher suites.
This PR will resolves #1037.
=> TKSS-1037: KonaSSLTlcpHandshakePerfTest adds cases on GCM cipher suites

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeCrypto.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2KeyPairGen.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2KeyAgreement.java, kona-crypto/src/main/jni/include/kona/kona_jni.h, kona-crypto/src/main/jni/kona_sm2_keypair.c, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM2Test.java
The native methods `sm2ToUncompPubKey`, `sm2GenPubKey` and `sm2ValidatePoint` in `NativeCrypto` can be static.
This PR will resolves #1042.
=> TKSS-1042: sm2ToUncompPubKey, sm2GenPubKey and sm2ValidatePoint can be static

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/DisabledAlgorithmConstraints.java
This is a backport of [JDK-8341964]: Add mechanism to disable different parts of TLS cipher suite.
This PR will resolves #1047.
[JDK-8341964]:
https://bugs.openjdk.org/browse/JDK-8341964
=> TKSS-1047: Backport JDK-8341964: Add mechanism to disable different parts of TLS cipher suite

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java
This is a backport of [JDK-8320743]: AEAD ciphers throw undocumented exceptions on overflow.
This PR will resolves #1048.
[JDK-8320743]:
https://bugs.openjdk.org/browse/JDK-8320743
=> TKSS-1048: Backport JDK-8320743: AEAD ciphers throw undocumented exceptions on overflow

kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPSSSignature.java
This is a backport of [JDK-8344024]: Unnecessary Hashtable usage in RSAPSSSignature.DIGEST_LENGTHS.
This PR will resolves #1050.
[JDK-8344024]:
https://bugs.openjdk.org/browse/JDK-8344024
=> TKSS-1050: Backport JDK-8344024: Unnecessary Hashtable usage in RSAPSSSignature.DIGEST_LENGTHS

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CounterMode.java
This is a backkport of [JDK-8344766]: AES/CTR slow at big payloads.
This PR will resolves #1054.
[JDK-8344766]:
https://bugs.openjdk.org/browse/JDK-8344766
=> TKSS-1054: Backport JDK-8344766: AES/CTR slow at big payloads

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLHandshake.java
This is a backport of [JDK-8345840]: Add missing TLS handshake messages to SSLHandshake.java.
This PR will resolves #1060.
[JDK-8345840]:
https://bugs.openjdk.org/browse/JDK-8345840
=> TKSS-1060: Backport JDK-8345840: Add missing TLS handshake messages to SSLHandshake.java

kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/keytool/Main.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/tools/keytool/Resources.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java
This is a backport of [JDK-8342062]: Reformat keytool and jarsigner output for keys with a named parameter set.
This PR will resolves #1061.
[JDK-8342062]:
https://bugs.openjdk.org/browse/JDK-8342062
=> TKSS-1061: Backport JDK-8342062: Reformat keytool and jarsigner output for keys with a named parameter set

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java
This is a backport of [JDK-8347596]: Update HSS/LMS public key encoding.
This PR will resolves #1062.
[JDK-8347596]:
https://bugs.openjdk.org/browse/JDK-8347596
=> TKSS-1062: Backport JDK-8347596: Update HSS/LMS public key encoding

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBES2Parameters.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/internal/interfaces/TlsMasterSecret.java
This is a backport of [JDK-8343467]: Remove unnecessary @SuppressWarnings annotations (security).
This PR will resolves #1059.
[JDK-8343467]:
https://bugs.openjdk.org/browse/JDK-8343467
=> TKSS-1059: Backport JDK-8343467: Remove unnecessary @SuppressWarnings annotations (security)

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4DecrypterPerfTest.java, kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4EncrypterPerfTest.java
`SM4EncrypterPerfTest` and `SM4DecrypterPerfTest` missed provider "KonaCrypto-NativeOneShot".
This PR will resolves #1076.
=> TKSS-1076: SM4 JMH tests should cover provider KonaCrypto-NativeOneShot

kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2CipherPerfTest.java, kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2SignaturePerfTest.java
`SM2SignaturePerfTest` and `SM2CipherPerfTest` should cover `KonaCrypto-NativeOneShot` as well.
This PR will resolvese #1078.
=> TKSS-1078: SM2 JMH tests missed provider KonaCrypto-NativeOneShot

gradle/wrapper/gradle-wrapper.properties, gradlew
Gradle 8.12 has been published for a while.
This PR will resolves #1084.
=> TKSS-1084: Upgrade Gradle to 8.12

kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2OneShotCipher.java, kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM2OneShotSignature.java, kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2SignatureTest.java
`SM2OneShotCipher` and`SM2OneShotSignature` would use `sm2OneShotXXX` methods.
This PR will resolves #1095.
=> TKSS-1095: SM2 OneShot implementations should use NativeCrypto sm2OneShot methods

kona-crypto/build.gradle.kts
`genJNIHeaders` task would generate the headers file in `src/main/jni/include/kona`.
This PR will resolves #1102.
=> TKSS-1102: Change the JNI headers output directory

kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlsHandshakePerfTest.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlsHandshakeWithSMPerfTest.java
Add a TLS JMH test with the international common algorithms, say `ECDSA` and `secp256r1`, on KonaSSL provider.
This PR will resolves #1111.
=> TKSS-1111: Add TLS JMH test with non-SM algorithms on KonaSSL

.github/workflows/build-pr.yml
The PR workflow could run tests against Kona JDK with the Action `setup-tencent-kona`.
This PR will resolves #1117.
=> TKSS-1117: Workflow supports Kona JDK

kona-crypto/src/test/java/com/tencent/kona/crypto/provider/KonaECKeyPairGeneratorTest.java
`KonaECKeyPairGeneratorTest` adds cases on `curveSM2`.
This PR will resolves #1123.
=> TKSS-1123: KonaECKeyPairGeneratorTest should cover SM2 curve

kona-crypto/README.md, kona-crypto/README_cn.md
- 修正了 EC 和 SM2 密钥对生成器实例化代码中的算法名称缺少引号的问题
- 在 `getInstance` 方法中添加了缺失的引号
=> docs(kona-crypto): 修复密钥对生成器实例化示例代码中的算法名称缺少引号的问题

gradle/libs.versions.toml, kona-crypto/build.gradle.kts, kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/ECKeyPairGenPerfTest.java, kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java
`ECKeyPairGenPerfTest` covers AWS ACCP.
This PR will resolves #1131.
=> TKSS-1131: ECKeyPairGenPerfTest involves ACCP

kona-pkix/src/jmh/java/com/tencent/kona/pkix/perf/KeyStorePerfTest.java, kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlcpHandshakePerfTest.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlsHandshakePerfTest.java, kona-ssl/src/jmh/java/com/tencent/kona/ssl/perf/KonaSSLTlsHandshakeWithSMPerfTest.java, kona-ssl/src/test/java/com/tencent/kona/ssl/TestUtils.java
PKIX and SSL JMH tests should move the TKSS providers to the top.
This PR will resolves #1133.
=> TKSS-1133: Make sure JMH tests use the target providers

kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/OCSP.java
This is a backport of [JDK-8347506]: Compatible OCSP readtimeout property with OCSP timeout.
This PR will resolves #1138.
[JDK-8347506]:
https://bugs.openjdk.org/browse/JDK-8347506
=> TKSS-1138: Compatible OCSP readtimeout property with OCSP timeout

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CertImpl.java
This is a backport of [JDK-8346094]: Harden X509CertImpl.getExtensionValue for NPE cases.
This PR will resolves #1141.
[JDK-8346094]:
https://bugs.openjdk.org/browse/JDK-8346094
=> TKSS-1141: Backport JDK-8346094: Harden X509CertImpl.getExtensionValue for NPE cases

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/HexDumpEncoder.java
This is a backport of [JDK-8349664]: HEX dump should always use ASCII or ISO_8859_1.
This PR will resolves #1142.
[JDK-8349664]:
https://bugs.openjdk.org/browse/JDK-8349664
=> TKSS-1142: Backport JDK-8349664: HEX dump should always use ASCII or ISO_8859_1

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/AlgorithmChecker.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/util/DisabledAlgorithmConstraints.java
This is a backport of [JDK-8346129]: Simplify EdDSA & XDH curve name usage.
This PR will resolves #1143.
[JDK-8346129]:
https://bugs.openjdk.org/browse/JDK-8346129
=> TKSS-1143: Backport JDK-8346129: Simplify EdDSA & XDH curve name usage

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Debug.java
This is a backport of [JDK-8351366]: Remove the java.security.debug=scl option.
This PR will resolves #1145.
[JDK-8351366]:
https://bugs.openjdk.org/browse/JDK-8351366
=> TKSS-1145: Backport JDK-8351366: Remove the java.security.debug=scl option

kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/AVA.java
This is a backport of [JDK-8349890]: option -Djava.security.debug=x509,ava breaks special chars.
This PR will resolves #1146.
[JDK-8349890]:
https://bugs.openjdk.org/browse/JDK-8349890
=> TKSS-1146: Backport JDK-8349890: option -Djava.security.debug=x509,ava breaks special chars

kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/MontgomeryIntegerPolynomialP256.java
This is a backport of [JDK-8353671]: Remove dead code missed in JDK-8350459.
This PR will resolves #1147.
[JDK-8353671]:
https://bugs.openjdk.org/browse/JDK-8353671
=> TKSS-1147: Backport JDK-8353671: Remove dead code missed in JDK-8350459

kona-crypto/src/main/java/com/tencent/kona/sun/security/rsa/RSAPadding.java, kona-crypto/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java
This is a backport of [JDK-8337692]: Better TLS connection support.
This is an vulnerability issue CVE-2025-21587, but it is related to RSA.
So, it should not affect the users of this project.
This PR will resolves #1148.
[JDK-8337692]:
https://github.com/openjdk/jdk21u/commit/d5c94adf69ba20f5652453729620c4f1c8e4860e
=> TKSS-1148: Backport JDK-8337692: Better TLS connection support

kona-pkix/src/main/java/com/tencent/kona/sun/security/util/DisabledAlgorithmConstraints.java, kona-pkix/src/main/java/com/tencent/kona/sun/security/util/SSLScope.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertSignAlgsExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateRequest.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/HandshakeContext.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/PostHandshakeContext.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/PreSharedKeyExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLAlgorithmConstraints.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSessionImpl.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ServerHello.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SessionTicketExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureAlgorithmsExtension.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Utilities.java
This is a backport of [JDK-8349583]: Add mechanism to disable signature schemes based on their TLS scope.
This PR will resolves #1144.
[JDK-8349583]:
https://bugs.openjdk.org/browse/JDK-8349583
=> TKSS-1144: Backport JDK-8349583: Add mechanism to disable signature schemes based on their TLS scope

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TrustStoreManager.java
This is a backport of [JDK-8310003]: Improve logging when default truststore is inaccessible.
This PR will resolves #1176.
[JDK-8310003]:
https://bugs.openjdk.org/browse/JDK-8310003
=> TKSS-1176: Backport JDK-8310003: Improve logging when default truststore is inaccessible

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/HelloCookieManager.java
This is a backport of [JDK-8360539]: DTLS handshakes fails due to improper cookie validation logic.
This PR will resolve #1194.
[JDK-8360539]:
https://bugs.openjdk.org/browse/JDK-8360539
=> Backport JDK-8360539: DTLS handshakes fails due to improper cookie validation logic

kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateMessage.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/CertificateVerify.java, kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Finished.java
This is a backport of[ JDK-8349594]: Enhance TLS protocol support.
This is a vulnerability issue with CVE-2025-30754.
This PR will resolve #1199.
[ JDK-8349594]:
https://github.com/openjdk/jdk21u/commit/bab305aff7bff5603507aa1516396728c1a1e146
=> TKSS-1199: Backport JDK-8349594: Enhance TLS protocol support
