- kona-crypto/build.gradle.kts
- kona-pkix/build.gradle.kts
- kona-provider/build.gradle.kts
- kona-ssl/build.gradle.kts
According to Maven Central requirements, a POM would contain name, description, URL and license.
[1] https://central.sonatype.org/publish/requirements
> TKSS-2: More information to POMs

- kona-crypto/build.gradle.kts
- kona-pkix/build.gradle.kts
- kona-provider/build.gradle.kts
- kona-ssl/build.gradle.kts
It would be better to deploy the artifacts to the Maven Central repository.
This PR will resolve #5
> TKSS-5: Deploy to Maven Central repository

- README.md
- README_cn.md
The artifacts are already uploaded to the Maven Central repository. It would be better to add a new section `Installation` for each README.
This PR will resolve #7.
> TKSS-7: Update READMEs on installation

- SECURITY.md
It would be better to set up a security policy, exactly SECURITY.md, for clarifying how to report the possible security vulnerabilities.
This PR will resolve #29.
> TKSS-29: Add security policy

- CONTRIBUTING.md
- CONTRIBUTING_cn.md
- README.md
- README_cn.md
- kona-crypto/README.md
- kona-crypto/README_cn.md
- kona-ssl/README.md
- kona-ssl/README_cn.md
The SM4 transformations on ECB mode are missing.
CONTRIBUTING.md adds a section on reporting security vulnerabilities.
This PR will resolve #33.
> TKSS-33: Update docs on SM4 transformations, contributing, etc.

- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4KeyGenerator.java
The substitution of org.bouncycastle.jcajce.provider.symmetric.SM4$KeyGen.
> TKSS-41: Implements SM4KeyGenerator

- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Parameters.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParametersTest.java
The substitution of org.bouncycastle.jcajce.provider.symmetric.SM4$AlgParams.
This PR will resolve #43.
> TKSS-43: Implements AlgorithmParameters for SM4

- README.md
- README_cn.md
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4GenParameterSpec.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4ParameterGenerator.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Parameters.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParameterGeneratorTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4ParametersTest.java
This is a substitution of org.bouncycastle.jcajce.provider.symmetric.SM4$AlgParamGen.
This PR will resolve #49.
> TKSS-49: Re-implements AlgorithmParameterGenerator for SM4

- README.md
- README_cn.md
- build.gradle.kts
- buildSrc/src/main/kotlin/kona-common.gradle.kts
Sign the jars with Oracle-issued JCE code signing certificate.
This PR will resolve #53.
> TKSS-53: Support Oracle JDK

- build.gradle.kts
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3KeyGenerator.java
Update version to 1.0.4-SNAPSHOT for developing the next release, exactly 1.0.4.
This PR will resolve #57.
> TKSS-57: Update version to 1.0.4-SNAPSHOT

- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherBlockChaining.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherCore.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherFeedback.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CipherTextStealing.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CounterMode.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/ElectronicCodeBook.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/FeedbackCipher.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GCM.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GCTR.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GHASH.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GaloisCounterMode.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/OutputFeedback.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PKCS5Padding.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/Padding.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Cipher.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Crypt.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Parameters.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SecureRandomHolder.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SymmetricCipher.java
- kona-crypto/src/main/java/com/tencent/kona/jdk/internal/misc/SharedSecretsUtil.java
- kona-crypto/src/main/java/com/tencent/kona/jdk/internal/misc/UnsafeUtil.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
This is a substitution of org.bouncycastle.jcajce.provider.symmetric.SM4$ECB.
This PR will resolve #51.
> TKSS-51: Re-implements SM4

- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECDHKeyAgreement.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECDSAOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECKeyPairGenerator.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/point/AffinePoint.java
This is a backport of [JDK-8295011]: EC point multiplication improvement for secp256r1.
This PR will resolve #90.
[JDK-8295011]:
<https://bugs.openjdk.org/browse/JDK-8295011>
> TKSS-90: Backport JDK-8295011: EC point multiplication improvement for secp256r1

- build.gradle.kts
> TKSS-93: Bump version to 1.0.4

- README.md
- README_cn.md
Update READMEs for changing the versions to 1.0.4.
> TKSS-95: Update versions in READMEs

- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/MutableIntegerModuloP.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial.java
This is a backport of [JDK-8295010]: Reduce if required in EC limbs operations.
This PR will resolve #100.
[JDK-8295010]:
<https://bugs.openjdk.org/browse/JDK-8295010>
> TKSS-100: TKSS-100: Backport JDK-8295010: Reduce if required in EC limbs operations

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2Test.java
This is a substitution of org.bouncycastle.jcajce.provider.asymmetric.ec.GMSignatureSpi.
This PR will resolve #98.
> TKSS-98: Re-implements SM2 Signature

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java
It would be better to directly use ECOperations::generatePrivateScalar to generate K values for SM2Signature.
This PR will resolve #112.
> TKSS-112: Enhancement on generating K values for SM2Signature

- kona-pkix/src/main/java/com/tencent/kona/sun/net/util/IPAddressUtil.java
This is a backport of JDK-8293598: Enhance InetAddress address handling.
Commit: https://github.com/openjdk/jdk17u/commit/0427ff40a3a130cb0f511029a41c4ae3313228cd
This PR will resolve #120.
> TKSS-120: Backport JDK-8293598: Enhance InetAddress address handling

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/SafeDHParameterSpec.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/SecurityProviderConstants.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/PredefinedDHParameterSpecs.java
This is a backport of JDK-8295723: security/infra/wycheproof/RunWycheproof.java fails with Assertion Error.
Commit: https://github.com/openjdk/jdk17u/commit/7d9a59088f2ba55334dd60db79a9d247b878fcab
> TKSS-123: Backport JDK-8295723: security/infra/wycheproof/RunWycheproof.java fails with Assertion Error

- build.gradle.kts
Update version to 1.0.5-SNAPSHOT for developing the next release, exactly 1.0.5.
> TKSS-130: Update version to 1.0.5-SNAPSHOT

- README.md
- README_cn.md
- build.gradle.kts
Update version to 1.0.5.
This PR will resolve #134.
> TKSS-134: Bump version to 1.0.5

- build.gradle.kts
Change version to 1.0.6-SNAPSHOT for development.
This PR will resolve #140.
> TKSS-140: Change version to 1.0.6-SNAPSHOT

- .github/workflows/gradle-build.yaml
It would be better to use GitHub actions for testing on PR.
This PR will resolve #59.
> TKSS-59: Add GitHub actions

- README.md
- README_cn.md
- build.gradle.kts
> TKSS-152: Bump version to 1.0.6

- build.gradle.kts
Change version to 1.0.7-SNAPSHOT for upcoming development.
This PR will resolve #154.
> TKSS-154: Change version to 1.0.7-SNAPSHOT

- README.md
- README_cn.md
It should mention Android is supported int the READMEs.
This PR will resolve #160.
> TKSS-160: Highlight Android in the docs

- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java
Add a new BouncyCastle interop test on SM2 key agreement algorithm.
This PR will resolve #164.
> TKSS-164: BouncyCastle interop test on SM2 key agreement

- kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM2CipherPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM2KeyAgreementPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM2KeyPairGenPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM2SignaturePerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM3HMacPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM3MessageDigestPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM4DecrypterPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/perf/SM4EncrypterPerfTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2WithBCTest.java
Add JMH tests for the ShangMi algorithm implementations from BouncyCastle.
This PR will resolve #166.
> TKSS-166: JMH tests on BouncyCastle SM algorithms

- README.md
- README_cn.md
- build.gradle.kts
Update the version to 1.0.7.
This PR will resolve #172.
> TKSS-172: Bump version to 1.0.7

- README.md
- README_cn.md
- build.gradle.kts
A bug fix version 1.0.7.1.
This PR will resolve #177.
> TKSS-177: Bump version to 1.0.7.1

- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECKeyPairGenerator.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECPrivateKeyImpl.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS8Key.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/InternalPrivateKey.java
This is a backport of [JDK-8305310]: Calculate PublicKey from PrivateKey.
This PR will resolve #190.
[JDK-8305310]:
<https://bugs.openjdk.org/browse/JDK-8305310>
> TKSS-190: Backport of JDK-8305310: Calculate PublicKey from PrivateKey

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/KeyUpdate.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLEngineImpl.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSocketImpl.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TransportContext.java
This is backport of [JDK-8294474]: Better AES support.
This PR will resolve #199.
[JDK-8294474]:
<https://github.com/openjdk/jdk17u/commit/13a90694f8177d4b6289f524ff5f721dbc3da09d>
> TKSS-199: Backport of JDK-8294474: Better AES support

- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/AdjacencyList.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/Builder.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/ForwardBuilder.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/ForwardState.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/State.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/SunCertPathBuilder.java
This is a backport of [JDK-8298310]: Enhance TLS session negotiation.
This PR will resolve #200.
[JDK-8298310]:
<https://github.com/openjdk/jdk17u/commit/0e679760884bb7315c38db37dddf4dfc90f4e1de>
> TKSS-200: Backport of JDK-8298310: Enhance TLS session negotiation

- kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GFMultiplier.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GFMultipliers.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/GHASH.java
It would try to enhance SM4-GCM performance with precomputed tables.
This PR will resolve #198.
> TKSS-198: Enhance SM4-GCM performance with precomputed tables

- build.gradle.kts
Update the version for releasing 1.0.8.
This PR will resolve #213.
> TKSS-213: Bump version to 1.0.8

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3Engine.java
Not iterate message bytes one by one may enhance SM3 engine performance a bit.
> TKSS-218: Enhance SM3 engine performance

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4EnginePerfTest.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Crypt.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM4Engine.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4EngineTest.java
It may be better to take round key as a member field of SM4Engine.
This PR will resolve #220.
> TKSS-220: Stateful SM4 engine

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/CounterMode.java
CounterMode would process output bytes in block rather than one by one.
This way may enhance the SM4-CTR performance a bit.
This PR will resolve #222.
> TKSS-222: Enhance SM4-CTR performance

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/ECOperatorPerfTest.java
Add JMH benchmarks on EC scalar multiplication.
This PR will resolve #224.
> TKSS-224: Add JMH benchmarks on EC scalar multiplication

- build.gradle.kts
Update version to 1.0.9-SNAPSHOT for developing the next release.
> TKSS-240: Update version to 1.0.9-SNAPSHOT

- README.md
- README_cn.md
- kona-demo/README.md
- kona-demo/README_cn.md
Update READMEs and add some FAQs.
This PR will resolve #247.
> TKSS-247: Add FAQs to READMEs

- README.md
- README_cn.md
> TKSS-249: Update FAQ

- kona-demo/build.gradle
- kona-demo/src/main/java/com/tencent/kona/demo/AppConfig.java
- kona-demo/src/main/java/com/tencent/kona/demo/KonaServer.java
- kona-demo/src/main/resources/application.yml
KonaServer in module kona-demo should support HTTP/2 via ALPN extension.
This PR will resolve #251.
> TKSS-251: KonaServer would support ALPN

- kona-ssl/src/test/java/com/tencent/kona/ssl/interop/JdkServer.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/misc/SysPropNamedGroupsTest.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SSLSocketTest.java
The system property com.tencent.kona.ssl.namedGroups may be renamed by accident.
It would be better to add a test to check that point.
This PR will resolve #260.
> TKSS-260: Check if system property com.tencent.kona.ssl.namedGroups is renamed

- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/CurveDB.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/HKDF.java
Although it is unnecessary to backport the [KEM feature] from OpenJDK, it need to sync the changes on some common files in that JBS.
This PR will resolve #264.
[KEM feature]:
<https://bugs.openjdk.java.net/browse/JDK-8297878>
> TKSS-264: Backport JDK-8297878: KEM: Implementation

- README.md
- README_cn.md
- kona-pkix/README.md
- kona-pkix/README_cn.md
The associated READMEs should introduce KeyTool.
This PR will resolve #276.
> TKSS-276: Update READMEs for KeyTool doc

- README.md
- README_cn.md
- kona-crypto/src/main/java/com/tencent/kona/com/sun/crypto/provider/HmacCore.java
- kona-crypto/src/main/java/com/tencent/kona/com/sun/crypto/provider/HmacPKCS12PBECore.java
- kona-crypto/src/main/java/com/tencent/kona/com/sun/crypto/provider/PKCS12PBECipherCoreUtil.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/HmacPKCS12PBE_SM3.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/PBEUtil.java
- kona-pkix/README.md
- kona-pkix/README_cn.md
- kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
- kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
It would support HmacPBESM3 for PKCS#12 keystore.
This PR will resolve #290.
> TKSS-290: PKCS12KeyStore supports HmacPBESM3

- build.gradle.kts
Update the version for the upcoming release 1.0.9.
This PR will resolve #296.
> TKSS-296: Update version to 1.0.9

- build.gradle.kts
Update the version 1.0.10-SNAPSHOT for the development on the next release 1.0.10.
> TKSS-300: Update version to 1.0.10-SNAPSHOT

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBEKey.java
It would clean the key when the [PBEKey] instance is not referenced any longer.
This PR will resolve #304.
[PBEKey]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-crypto/src/main/java/com/tencent/kona/crypto/provider/PBEKey.java>
> TKSS-304: The key in PBEKey should be cleaned

- kona-ssl/src/test/java/com/tencent/kona/ssl/peers/SunJSSEClient.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/peers/SunJSSEServer.java
It would provider a testing server and client with SunJSSE provider.
This PR will resolve #312.
> TKSS-312: Provider SunJSSE peers

- kona-ssl/build.gradle.kts
- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithTomcatDemo.java
It would add a demo on integrating KonaSSL to Tomcat server on TLS.
This PR will resolve #328.
> TKSS-328: Add TLS demo for Tomcat

- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithTomcatDemo.java
t would add a demo on integrating KonaSSL to Tomcat server on TLCP.
This PR will resolve #348.
> TKSS-348: Add TLCP demo for Tomcat

- kona-demo/build.gradle
- kona-demo/src/main/java/com/tencent/kona/demo/AppConfig.java
- kona-demo/src/main/java/com/tencent/kona/demo/JettyServer.java
- kona-demo/src/main/java/com/tencent/kona/demo/TomcatServer.java
- kona-demo/src/main/resources/application.yml
- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithTomcatDemo.java
The Spring Boot project `kona-demo` would add a Tomcat server.
This PR will resolve #352.
> TKSS-352: kona-demo supports Tomcat

- README.md
- README_cn.md
- kona-demo/README.md
- kona-demo/README_cn.md
It would update READMEs for clarifying demos clearly.
This PR will resolves #354.
> TKSS-354: Update docs on demos

- README.md
- README_cn.md
- kona-ssl/build.gradle.kts
- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithOkHttpDemo.java
Add a demo with OkHttp on TLS 1.3.
This PR will resolves #360.
> TKSS-360: Add TLS demo for OkHttp

- README.md
- README_cn.md
Update FAQs on wordings and content.
This PR will resolves #364.
> TKSS-364: Update FAQs

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSocketImpl.java
This is a backport of [JDK-8315422]: getSoTimeout() would be in try block in SSLSocketImpl.
This PR will resolve #373.
[JDK-8315422]:
<https://bugs.openjdk.org/browse/JDK-8315422>
> TKSS-373: Backport JDK-8315422: getSoTimeout() would be in try block in SSLSocketImpl

- buildSrc/src/main/kotlin/kona-common.gradle.kts
- gradle/libs.versions.toml
- kona-crypto/build.gradle.kts
- kona-demo/build.gradle
- kona-pkix/build.gradle.kts
- kona-provider/build.gradle.kts
- kona-ssl/build.gradle.kts
It would be better to leverage Gradle version catalog and TOML file to share dependency versions between modules.
This PR will resolve #375.
> TKSS-375: Share dependency versions

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2CipherConstantTimeTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2SignatureConstantTimeTest.java
It would be better to add JMH tests for checking if SM2 is constant-time.
This PR will resolve #379.
> TKSS-379: Add JMH tests for checking constant-time issue on SM2

- README.md
- kona-crypto/README.md
- kona-pkix/README.md
- kona-pkix/README_cn.md
- kona-pkix/src/test/resources/certs/ee-rsarsa-rsarsa-rsarsa.crt
- kona-pkix/src/test/resources/certs/intca-rsarsa-rsarsa.crt
- kona-provider/README.md
- kona-ssl/README.md
- kona-ssl/src/test/resources/certs/ee-rsarsa-rsarsa-rsarsa.crt
- kona-ssl/src/test/resources/certs/intca-rsarsa-rsarsa.crt
It would be better to remove the trailing spaces.
This PR will resolves #381.
> TKSS-381: Remove trailing spaces

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4ConstantTimeTest.java
It would be better to add JMH tests for checking if SM4 is constant-time.
This PR will resolves #383.
> TKSS-383: Add JMH tests for checking constant-time issue on SM4

- README.md
- README_cn.md
- gradle/libs.versions.toml
- kona-ssl/build.gradle.kts
- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLSWithGRPCDemo.java
- kona-ssl/src/test/proto/message.proto
It would be better to add a demo with grpc-java on TLS 1.3/RFC 8998.
This PR will resolves #388.
> TKSS-388: Add TLS demo with gRPC

- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithGRPCDemo.java
It would be better to add a demo with gRPC on TLCP.
This PR will resolves #390.
> TKSS-390: Add TLCP demo with gRPC

- README.md
- README_cn.md
Just add some [Shields badges] to the main README for highlighting the latest release and Maven Central artifacts.
This PR will resolves #392.
[Shields badges]:
<https://shields.io/badges>
> TKSS-392: Add Shields badges to the main README

- .github/workflows/build-pr.yml
`gradle-build.yaml` --> `build-pr.yml`
This PR will resolves #398.
> TKSS-398: `gradle-build.yaml` --> `build-pr.yml`

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3HMac.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java
SM3 HMAC would support clone.
This PR will resolves #404.
> TKSS-404: SM3 HMAC supports clone

- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
It would be better to add the empty or null input test cases for SM4.
This PR will resolves #412.
> TKSS-412: Add empty or null input test cases for SM4

- build.gradle.kts
- buildSrc/src/main/kotlin/CommonTest.kt
- buildSrc/src/main/kotlin/kona-common.gradle.kts
It could apply Gradle toolchain feature to test with different JDK distributions.
This PR will resolves #422.
> TKSS-420: Test with different JDKs

- kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyStoreToolTest.java
- kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithHttpClientDemo.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/demo/TLCPWithoutCertValidationDemo.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/BabaSSLServerJdkClientTest.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerBabaSSLClient.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tls/BabaSSLServerJdkClientTest.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tls/JdkServerBabaSSLClientTest.java
All the temp files generated by the tests should be in the corresponding build directories.
This PR will resolves #440.
> TKSS-440: The temp test files should be in build directories

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/ECOperatorPerfTest.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Engine.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyPairGenerator.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/util/Constants.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/SM2Operations.java
It may be better to make a separated SM2Operations.
This PR will resolves #451.
> TKSS-451: Decouple SM2 operations from ECOperations

- build.gradle.kts
Bump version for releasing 1.0.10.
This PR will resolves #468.
> TKSS-468: Update version to 1.0.10

- build.gradle.kts
Just update version to `1.0.11-SNAPSHOT` for the next release development.
This PR will resolves #470.
> TKSS-470: Update version to 1.0.11-SNAPSHOT

- kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PrivateKeySpec.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2PublicKeySpec.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2SignatureParameterSpec.java
Some improvements on classes in package `com.tencent.kona.crypto.spec`.
This PR will resolves #484.
> TKSS-484: Enhance com.tencent.kona.crypto.spec classes

- kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2PrivateKey.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2PublicKey.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyFactoryTest.java
It would re-work `SM2PrivateKey` and `SM2PublicKey` to enhance the parameter checks.
This PR will resolves #500.
> TKSS-500: Enhance SM2PrivateKey and SM2PublicKey

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyAgreementTest.java
`SM2KeyAgreement` should check if the peer public key is valid before deriving the shared key.
This PR will resolves #508.
> TKSS-508: SM2KeyAgreement should check peer public key

- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacKeyGeneratorTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4KeyGeneratorTest.java
Add new tests for `SM3HMacKeyGenerator` and `SM4KeyGenerator`.
This PR will resolves #516.
> TKSS-516: Add symmetrical key generator tests

- README.md
- README_cn.md
The badges in READMEs needs to be updated for 1.0.10.
This PR will resolves #519.
> TKSS-519: Update READMEs for 1.0.10

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2KeyAgreement.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/spec/SM2KeyAgreementParamSpec.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM2KeyAgreementTest.java
`SM2KeyAgreement` should validate the private key range.
This PR will resolves #532.
> TKSS-532: SM2KeyAgreement should check private key

- buildSrc/src/main/kotlin/kona-common.gradle.kts
When use tasks `testOnXXX`, it should always use JDK 8 to compile Java source.
Otherwise, the below error would raise,
`java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer`
This PR will resolves #546.
> TKSS-546: Gradle toolchain should always use JDK 8 to compile Java source

- kona-pkix/src/test/java/com/tencent/kona/pkix/tool/KeyToolTest.java
`KeyToolTest` should check the generated cert's more details, including pubic key algorithm, signature algorithm and named groups.
And it also should output the option details.
This PR will resolves #553.
> TKSS-553: KeyToolTest should check more details

- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
`SM3Test` adds cases on `MessageDigest::digest(byte[] buf, int offset, int len)`.
This PR will resolves #572.
> TKSS-572: SM3 tests on MessageDigest::digest(byte[] buf, int offset, int len)

- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3HMacTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM3Test.java
`SM3HMacTest` adds cases for checking the bounds of input and output buffer.
This PR will resolves #574.
> TKSS-574: SM3HMacTest adds cases on checking bounds

- buildSrc/src/main/kotlin/CommonTest.kt
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4EngineTest.java
It would be better to print BabaSSL version information when checking this tool.
> TKSS-590: Print BabaSSL version

- kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SSLSocketOnTLS12Test.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tls/SSLSocketOnTLS13Test.java
Add a test for applying ShangMi certificate, `curveSM2` and `sm2sig_sm3` on TLS 1.2.
> TKSS-592: Add test on TLS 1.2

- kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
It should limit the size of `entryCache` in `PKCS12KeyStore` and make sure the keys are lower-case with `Locale.English`.
And the cache entries could be GCed if the memory is not sufficient.
This PR will resolves #608.
> TKSS-608: Enhance store entry cache in PKCS12KeyStore

- kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
`PKCS12Keystore` would use `com.tencent.kona.sun.security.util.Cache` to build `storeEntryCache`.
This PR will resolves #610.
> TKSS-610: PKCS12Keystore storeEntryCache would use Cache utility

- kona-pkix/src/test/java/com/tencent/kona/pkix/provider/KeyStoreProfTest.java
Add a test for profiling the performance on getting entries from key store.
This PR will resolves #631.
> TKSS-631: Add test for profiling key store performance

- kona-pkix/src/main/java/com/tencent/kona/sun/security/provider/certpath/ForwardBuilder.java
This is a backport of [JDK-8308204]: Enhanced certificate processing.
This PR will resolves #640.
[JDK-8308204]:
https://github.com/openjdk/jdk17u/commit/6a1d2f21e6df1f0d7ee273853e15b8deac07076a
> TKSS-640: Backport JDK-8308204: Enhanced certificate processing

- kona-pkix/src/main/java/com/tencent/kona/sun/security/util/KeyUtil.java
This is a backport of [JDK-8317547]: Enhance TLS connection support.
This PR will resolves #642.
[JDK-8317547]:
https://github.com/openjdk/jdk21u/commit/e831175ecf54edab00820e9a10e134ca96b7b9df
> TKSS-642: Backport JDK-8317547: Enhance TLS connection support

- README.md
- README_cn.md
- build.gradle.kts
Update version for releasing 1.0.11.
This PR will resolves #647.
> TKSS-647: Bump version to 1.0.11

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificateVerify.java
It would be better to remove the codes that are not related to TLCP from TLCPCertificateVerify.
This PR will resolves #652.
> TKSS-652: Simplify TLCPCertificateVerify

- build.gradle.kts
Update version for developing the next release 1.0.12.
This PR will resolves #656 .
> TKSS-656: Update version to 1.0.12-SNAPSHOT

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SM2EServerKeyExchange.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java
Remove codes on TLS 1.2 from SM2EServerKeyExchange.
This PR will resolves #674.
> TKSS-674: Simplify SM2EServerKeyExchange

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/DerOutputStream.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS9Attribute.java
- kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs/PKCS9Attributes.java
This is a backport of [JDK-8265372]: Simplify PKCS9Attribute.
This PR will resolves #683.
[JDK-8265372]:
https://bugs.openjdk.org/browse/JDK-8265372
> TKSS-683: Backport JDK-8265372: Simplify PKCS9Attribute

- kona-pkix/src/main/java/com/tencent/kona/sun/security/pkcs12/PKCS12KeyStore.java
This is a backport of [JDK-8327461]: KeyStore getEntry is not thread-safe.
[JDK-8327461]:
https://bugs.openjdk.org/browse/JDK-8327461
> TKSS-705: Backport JDK-8327461: KeyStore getEntry is not thread-safe

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Debug.java
This is a backport of [JDK-8327818]: Implement Kerberos debug with sun.security.util.Debug.
[JDK-8327818]:
https://bugs.openjdk.org/browse/JDK-8327818
> TKSS-756: Backport JDK-8327818: Implement Kerberos debug with sun.security.util.Debug

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Debug.java
This is a backport of [JDK-8051959]: Add thread and timestamp options to java.security.debug system property.
This PR will resolves #754.
[JDK-8051959]:
https://bugs.openjdk.org/browse/JDK-8051959
> TKSS-754: Backport JDK-8051959: Add thread and timestamp options to java.security.debug system property

- README.md
- README_cn.md
- build.gradle.kts
Update version for the next release 1.0.12.
This PR will resolves #759.
> TKSS-759: Bump version to 1.0.12

- build.gradle.kts
Update version to 1.0.13-SNAPSHOT for developing the next release.
> TKSS-767: Update version to 1.0.13-SNAPSHOT

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialSM2.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/SM2OrderField.java
`IntegerPolynomialSM2` and `SM2OrderField` are generated by `FieldGen`, and the copyright notes should not be Tencent's.
This PR will resolves #774.
> TKSS-774: Update IntegerPolynomialSM2 and SM2OrderField copyright notes

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM2Signature.java
- kona-crypto/src/main/java/com/tencent/kona/java/lang/MathUtil.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECDHKeyAgreement.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECDSAOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/ECOperations.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/point/AffinePoint.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/ec/point/ProjectivePoint.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/IntegerMontgomeryFieldModuloP.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/Curve25519OrderField.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/Curve448OrderField.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial25519.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial448.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialModBinP.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP256.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP384.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialP521.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomialSM2.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/MontgomeryIntegerPolynomialP256.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P256OrderField.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P384OrderField.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/P521OrderField.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/SM2OrderField.java
- kona-crypto/src/test/java/com/tencent/kona/sun/security/util/math/intpoly/FieldGen.java
This is a backport of [JDK-8329538]: Accelerate P256 on x86_64 using Montgomery intrinsic.
This PR will resolves #755.
[JDK-8329538]:
https://bugs.openjdk.org/browse/JDK-8329538
> TKSS-755: Backport JDK-8329538: Accelerate P256 on x86_64 using Montgomery intrinsic

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/IntegerMontgomeryFieldModuloP.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/IntegerPolynomial.java
- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/math/intpoly/MontgomeryIntegerPolynomialP256.java
This is a backport of [JDK-8333046]: Clean codes in sun.security.util.math.
This PR will resolves #793.
[JDK-8333046]:
https://bugs.openjdk.org/browse/JDK-8333046
> TKSS-793: Backport JDK-8333046: Clean codes in sun.security.util.math

- README.md
- README_cn.md
Tencent Kona JDK 8 already implements ShangMi algorithms and protocols.
Update README for these changes.
This PR will resolves #799.
> TKSS-799: Update README for ShangMi features in Tencent Kona JDK

- README.md
- README_cn.md
- build.gradle.kts
Update version for the next release 1.0.13.
This PR will resolves #822.
> TKSS-822: Bump version to 1.0.13

- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/SM3Engine.java
`SM3Engine` should not copy a word from the input in some cases. This can improve performance by about 3%.
This PR will resolves #824 .
> Enhance SM3 engine performance

- build.gradle.kts
Update version to 1.0.14-SNAPSHOT for developing the next release.
This PR will resolves #826.
> TKSS-826: Update version to 1.0.14-SNAPSHOT

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4EnginePerfTest.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/AlgoCipher.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/CipherCore.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/ConstructKeys.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/DataWindow.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/Mode.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeCrypto.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4Engine.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/Padding.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Cipher.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Crypt.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Params.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SymmetricCipher.java
- kona-crypto/src/main/jni/kona_crypto.c
- kona-crypto/src/main/jni/kona_crypto.h
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4EngineTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/nativeImpl/NativeSM4Test.java
Provide new `SM4` implementation based on `OpenSSL` `libcrypto` lib.
But this implementation is not enabled by default.
This PR will resolves #861.
> TKSS-861: SM4 implementation based on OpenSSL

- README.md
- README_cn.md
- kona-crypto/README.md
- kona-crypto/README_cn.md
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/NativeCrypto.java
Provides new SM3 and SM4 implementations based on OpenSSL, the READMEs should be updated accordingly.
This PR will resolves #865.
> TKSS-865: Update READMEs for the implementations based on OpenSSL

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ClientHello.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/DTLSInputRecord.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/ServerHandshakeContext.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TransportContext.java
This is a backport of [JDK-8307383]: Enhance DTLS connections.
Commit: https://github.com/openjdk/jdk21u/commit/3c46e9918ba480f58abeb524139c403bb2c2cee7
This PR will resolves #889.
[JDK-8307383]:
https://bugs.openjdk.org/browse/JDK-8307383
> TKSS-889: Backport JDK-8307383: Enhance DTLS connections

- README.md
- README_cn.md
- build.gradle.kts
Update the version for releasing 1.0.14.
> TKSS-891: Update version to 1.0.14

- buildSrc/src/main/kotlin/kona-common.gradle.kts
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
It would be better to decouple the provider initialization from the internal classes.
This can help this project works on GraalVM.
This PR will resolves #904.
> TKSS-904: Simplify provider initialization

- kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoInsts.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/KonaCryptoProviderTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java
- kona-demo/src/main/java/com/tencent/kona/demo/JettyServer.java
- kona-demo/src/main/java/com/tencent/kona/demo/TomcatServer.java
- kona-pkix/src/test/java/com/tencent/kona/pkix/TestUtils.java
- kona-provider/src/test/java/com/tencent/kona/TestUtils.java
- kona-provider/src/test/java/com/tencent/kona/pkix/SignatureDemo.java
- kona-provider/src/test/java/com/tencent/kona/ssl/TLCPWithJettyDemo.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/TestUtils.java
If the providers from TencentKonaSMSuite have lower priorities, they may call the implementations from other providers, say JDK or BouncyCastle.
This PR will resolves #909.
> TKSS-909: It would not depend on other providers

- build.gradle.kts
Change the version to 1.0.15.
This PR will resolves #913.
> TKSS-913: Bump version to 1.0.15

- README.md
- README_cn.md
- build.gradle.kts
Update version for developing the next release `1.0.16`.
This PR will resolves #915.
> TKSS-915: Update version to 1.0.16-SNAPSHOT

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/StatusResponseManager.java
This is a backport of [JDK-8339403]: sun.security.ssl.StatusResponseManager.get swallows interrupt status.
This PR will resolves #924.
[JDK-8339403]:
https://bugs.openjdk.org/browse/JDK-8339403
> TKSS-924: Backport JDK-8339403: sun.security.ssl.StatusResponseManager.get swallows interrupt status

- kona-pkix/src/main/java/com/tencent/kona/sun/security/x509/X509CRLImpl.java
This is a backport of [JDK-8336665]: CCE in X509CRLImpl$TBSCertList.getCertIssuer.
This PR will resolves #925.
[JDK-8336665]:
https://bugs.openjdk.org/browse/JDK-8336665
> TKSS-925: Backport JDK-8336665: CCE in X509CRLImpl$TBSCertList.getCertIssuer

- kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoInsts.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoNativeProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoProvider.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/KonaCryptoProviderTest.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java
A new provider for native crypto based on OpenSSL.
This PR will resolves #975.
> TKSS-975: New crypto provider based on OpenSSL

- kona-pkix/src/main/java/com/tencent/kona/pkix/KonaPKIXProvider.java
- kona-provider/src/main/java/com/tencent/kona/KonaProvider.java
- kona-ssl/src/main/java/com/tencent/kona/ssl/KonaSSLProvider.java
`KonaPKIXProvider`, `KonaSSLProvider` and `KonaProvider` provide singleton instances.
This PR will resolve #977.
> TKSS-977: Singleton provider instances

- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2CipherConstantTimeTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2CipherPerfTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2KeyAgreementPerfTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2KeyPairGenPerfTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2SignatureConstantTimeTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM2SignaturePerfTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM3HMacPerfTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM3MessageDigestPerfTest.java
- kona-crypto/src/jmh/java/com/tencent/kona/crypto/perf/SM4ConstantTimeTest.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoInsts.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoNativeOneShotProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/KonaCryptoNativeProvider.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4Cipher.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SM4OneShotCrypt.java
- kona-crypto/src/main/java/com/tencent/kona/crypto/provider/nativeImpl/SymmetricCipher.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/TestUtils.java
- kona-crypto/src/test/java/com/tencent/kona/crypto/provider/SM4Test.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/TlcpHandshakeProfTest.java
Provide a new native SM4 cipher, which doesn't use GC to manage the native memory.
This PR will resolves #1072.
> Provide one-shot native SM4 cipher

- README.md
- README_cn.md
- kona-crypto/README.md
- kona-crypto/README_cn.md
It needs to update the READMEs for the new provider `KonaCrypto-NativeOneShot`.
This PR will resolves #1074.
> TKSS-1074: Update READMDs on KonaCrypto-NativeOneShot

- README.md
- README_cn.md
- build.gradle.kts
Update version for releasing 1.0.16.
This PR will resolves #1080.
> TKSS-1080: Bump version to 1.0.16

- build.gradle.kts
Update version to `1.0.17-SNAPSHOT` for developing the next release.
This PR will resolves #1082.
> TKSS-1082: Update version to 1.0.17-SNAPSHOT

- gradle/libs.versions.toml
BouncyCastle 1.80 has been published.
This PR will resolves #1086.
> TKSS-1086: Upgrade BouncyCastle to 1.80

- kona-crypto/README.md
- kona-crypto/README_cn.md
Update READMEs for introducing `com.tencent.kona.defaultCrypto`.
This PR will resolves #1094.
> Update doc for system property com.tencent.kona.defaultCrypto

- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLConfiguration.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SignatureScheme.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/Utilities.java
This is a backport of [JDK-8280494]: (D)TLS signature schemes.
This PR will resolves #1159.
[JDK-8280494]:
https://bugs.openjdk.org/browse/JDK-8280494
> TKSS-1159: Backport JDK-8280494: (D)TLS signature schemes

- build.gradle.kts
Update version for releasing 1.0.17.
This PR will resolves #1162.
> TKSS-1162: Bump version to 1.0.17

- build.gradle.kts
Update version to 1.0.18-SNAPSHOT for developing the next release.
This PR will resolves #1164.
> TKSS-1164: Update version to 1.0.18-SNAPSHOT

- kona-crypto/src/main/java/com/tencent/kona/sun/security/util/Debug.java
This is a backport of [JDK-8350689]: Turn on timestamp and thread metadata by default for java.security.debug.
This PR will resolve #1181.
[JDK-8350689]:
https://bugs.openjdk.org/browse/JDK-8350689
> TKSS-1181: Backport JDK-8350689: Turn on timestamp and thread metadata by default for java.security.debug

- kona-crypto/src/main/java/com/tencent/kona/crypto/CryptoUtils.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/PreSharedKeyExtension.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SSLSessionImpl.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/SessionTicketExtension.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPAuthentication.java
- kona-ssl/src/main/java/com/tencent/kona/sun/security/ssl/TLCPCertificate.java
- kona-ssl/src/test/java/com/tencent/kona/ssl/tlcp/JdkServerJdkClientTest.java
This is a backport of [JDK-8357033]: Reduce stateless session ticket size.
This PR will resolve #1178.
[JDK-8357033]:
https://bugs.openjdk.org/browse/JDK-8357033
> TKSS-1178: Backport JDK-8357033: Reduce stateless session ticket size

- build.gradle.kts
Update the version for releasing 1.0.18.
This PR will resolve #1201.
> TKSS-1201: Bump version to 1.0.18
